-- DinoWar — catálogo de cartas. GENERADO por
-- `node tools/generar-cartas.mjs` desde src/data/cards.js,
-- src/data/balance.js y src/data/coleccion.js. **No editar a mano.**
--
-- El servidor necesita esto para tres cosas que no puede preguntarle al
-- cliente: si un mazo respeta las rarezas, si las cartas que lleva son
-- tuyas de verdad, y con qué colección empieza una cuenta nueva. Un test
-- comprueba que este fichero es el que saldría hoy del código.

create table if not exists public.catalogo_cartas (
  card_id      text primary key,
  tipo         text not null,
  rareza       text not null,
  -- Copias que caben en un mazo. Es a la vez el límite de construcción y
  -- la escala de rareza: la misma regla mirada desde dos sitios.
  copias_max   int  not null check (copias_max > 0),
  valor_fusion int  not null check (valor_fusion >= 0),
  -- Las de jefe se ganan cooperando, no salen en sobres y no se funden.
  es_jefe      boolean not null default false
);

-- Con qué colección empieza una cuenta. Es justo el mazo de referencia:
-- lo necesario para jugar desde el primer minuto y ni una carta más.
create table if not exists public.catalogo_inicial (
  card_id  text primary key references public.catalogo_cartas (card_id),
  copias   int not null check (copias > 0)
);

-- Los mazos iniciales: uno se elige al crear la cuenta y es la colección
-- de salida entera. `private.sembrar_inicial` (0023) lee de aquí; el
-- cliente sólo manda el id del mazo. Sale de src/data/iniciales.js.
create table if not exists public.catalogo_iniciales (
  mazo     text not null,
  nombre   text not null,
  card_id  text not null references public.catalogo_cartas (card_id),
  copias   int not null check (copias > 0),
  primary key (mazo, card_id)
);

-- La tienda: lo que se vende y cuánto cuesta. `comprar_cosmetico` (0024) cobra
-- el precio de AQUÍ; el cliente sólo manda el id. Sale de src/data/cosmeticos.js.
create table if not exists public.catalogo_cosmeticos (
  id           text primary key,
  tipo         text not null,
  precio       int  not null check (precio >= 0),
  por_defecto  boolean not null default false
);
-- Lo exclusivo cuesta 0 y NO se compra ni es de todos: lo otorga un logro.
-- La columna llegó después de la tabla (0027), de ahí el `add column`.
alter table public.catalogo_cosmeticos
  add column if not exists exclusivo boolean not null default false;

-- Los precios, en una fila. Que sean una tabla y no constantes en el SQL
-- permite tocarlos sin volver a desplegar nada.
create table if not exists public.catalogo_economia (
  id                int primary key default 1 check (id = 1),
  precio_sobre      int not null,
  cartas_por_sobre  int not null,
  monedas_inicio    int not null,
  monedas_victoria  int not null,
  monedas_derrota   int not null,
  tamano_mazo       int not null,
  mazos_maximo      int not null
);

-- Criaturas legendarias que caben en un mazo, entre todas. La columna
-- llegó después de la tabla, de ahí el `add column`: sin él una base ya
-- creada se queda sin ella y `validar_mazo` no puede leer el tope.
alter table public.catalogo_economia
  add column if not exists legendarias_dino_max int not null default 3;

-- El crafteo: cuántas esquirlas da fundir una copia sobrante y cuántas cuesta
-- crear una, por rareza. `fundir_excedente` y `crear_carta` (0029) leen de
-- AQUÍ; el cliente sólo manda el id. Sale de src/data/crafteo.js.
create table if not exists public.catalogo_crafteo (
  rareza  text primary key,
  fundir  int not null check (fundir > 0),
  crear   int not null check (crear > 0)
);

-- Los TORNEOS. `entrar_en_torneo` (0038) cobra la entrada de AQUÍ y valida
-- el mazo contra la lista de cartas legales de AQUÍ: si la regla viajara en
-- la petición, el mazo se autorizaría a sí mismo. Sale de src/data/torneos.js.
--
-- La regla NO se traduce a SQL: se vuelca ya resuelta, como una LISTA de ids
-- legales. Traducir `soloClados` o `costeMax` a un `where` pediría columnas de
-- clado y coste en `catalogo_cartas` y un segundo sitio donde el vocabulario
-- puede quedarse atrás del de `torneos.js`. Una lista generada no se
-- contradice con su origen: o está o no está.
create table if not exists public.catalogo_torneos (
  id          text primary key,
  nombre      text not null,
  -- Sitio en la rotación. La semana la calcula el servidor y el torneo de
  -- hoy es el de `semana mod (cuántos hay)`, el mismo cálculo que hace
  -- `torneoDe()` en el navegador.
  orden       int  not null unique,
  -- Copias por carta si el torneo las recorta; null es el tope de rareza de
  -- siempre. Es el único campo de la regla que una lista de ids no expresa.
  copias_max  int  check (copias_max > 0)
);

create table if not exists public.catalogo_torneo_cartas (
  torneo   text not null references public.catalogo_torneos (id) on delete cascade,
  card_id  text not null references public.catalogo_cartas (card_id),
  primary key (torneo, card_id)
);

-- Lo que paga una racha por victorias. Lo cobra `duelo_cerrar` al cerrarla.
create table if not exists public.catalogo_torneo_premios (
  victorias int primary key check (victorias >= 0),
  monedas   int not null check (monedas >= 0),
  sobres    int not null check (sobres >= 0)
);

-- La entrada y los dos topes de la racha, con el resto de los precios.
alter table public.catalogo_economia
  add column if not exists torneo_entrada int not null default 50,
  add column if not exists torneo_victorias int not null default 5,
  add column if not exists torneo_derrotas int not null default 3;

insert into public.catalogo_cartas (card_id, tipo, rareza, copias_max, valor_fusion, es_jefe) values
  ('dryosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('ornitholestes', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('ceratosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('stegosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('allosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('camarasaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('diplodocus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('apatosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('torvosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('nodosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('riparovenator', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('lokiceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('brachylophosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('tyrannotitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('huaxiadraco', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('gregarismo', 'EVENTO', 'RARO', 3, 12, false),
  ('gastrolitos', 'EVENTO', 'EPICO', 2, 35, false),
  ('crecimiento_acelerado', 'EVENTO', 'LEGENDARIO', 1, 100, false),
  ('neumaticidad', 'EVENTO', 'EPICO', 2, 35, false),
  ('fractura', 'EVENTO', 'EPICO', 2, 35, false),
  ('competencia', 'EVENTO', 'EPICO', 2, 35, false),
  ('trampa', 'EVENTO', 'RARO', 3, 12, false),
  ('mortandad', 'EVENTO', 'LEGENDARIO', 1, 100, false),
  ('sabana_helechos', 'EVENTO', 'COMUN', 3, 4, false),
  ('inundacion', 'EVENTO', 'RARO', 3, 12, false),
  ('canal_trenzado', 'EVENTO', 'RARO', 3, 12, false),
  ('bosque_ribereno', 'EVENTO', 'EPICO', 2, 35, false),
  ('deriva_arida', 'EVENTO', 'EPICO', 2, 35, false),
  ('nido', 'EVENTO', 'COMUN', 3, 4, false),
  ('tormenta_polvo', 'EVENTO', 'RARO', 3, 12, false),
  ('avenida_lodo', 'EVENTO', 'EPICO', 2, 35, false),
  ('enterramiento', 'EVENTO', 'RARO', 3, 12, false),
  ('cauce_abandonado', 'EVENTO', 'COMUN', 3, 4, false),
  ('barrera_troncos', 'EVENTO', 'COMUN', 3, 4, false),
  ('ceniza', 'EVENTO', 'RARO', 3, 12, false),
  ('sedimento', 'EVENTO', 'EPICO', 2, 35, false),
  ('osario', 'EVENTO', 'RARO', 3, 12, false),
  ('carroneros', 'EVENTO', 'COMUN', 3, 4, false),
  ('oleada', 'EVENTO', 'COMUN', 3, 4, false),
  ('estampida', 'EVENTO', 'EPICO', 2, 35, false),
  ('migracion', 'EVENTO', 'RARO', 3, 12, false),
  ('crecida_delta', 'EVENTO', 'RARO', 3, 12, false),
  ('cantera', 'RECURSO', 'EPICO', 2, 35, false),
  ('incendio', 'EVENTO', 'RARO', 3, 12, false),
  ('acuifero', 'EVENTO', 'EPICO', 2, 35, false),
  ('rebrote', 'RECURSO', 'RARO', 3, 12, false),
  ('carrona', 'RECURSO', 'LEGENDARIO', 1, 100, false),
  ('lago', 'RECURSO', 'EPICO', 2, 35, false),
  ('insectos', 'RECURSO', 'COMUN', 3, 4, false),
  ('manada_paso', 'RECURSO', 'RARO', 3, 12, false),
  ('frutos', 'RECURSO', 'RARO', 3, 12, false),
  ('llanura', 'CLIMA', 'EPICO', 2, 35, false),
  ('canal', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('bosque', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('aridez', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('sabana', 'CLIMA', 'COMUN', 3, 4, false),
  ('plesiopleurodon', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('ojoraptorsaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('dromaeosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('athenar', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('sanjuansaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('suchomimus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('eosinopteryx', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('troodon', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('carnotaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('spinosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('mosasaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('halszkaraptor', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('tongtianlong', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('scanisaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('monolophosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('invictarx', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('medusaceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('platyceratops', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('loricatosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('therizinosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('alaskacephale', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('titanoceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('atlasaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('stegoceras', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('maiasaura', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('edmontosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('plateosauravus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('gargoyleosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('wendiceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('antarctosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('liaoceratops', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('rhinorex', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('bienosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('shuangmiaosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('chasmosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('tyrannosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('velociraptor', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('brachiosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('argentinosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('mamenchisaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('amargasaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('ankylosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('kentrosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('euoplocephalus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('triceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('pachycephalosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('iguanodon', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('parasaurolophus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('pteranodon', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('quetzalcoatlus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('elasmosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('gallimimus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('thescelosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('deinocheirus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('anzu', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('nigersaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('shuvuuia', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('saurolophus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('tarbosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('psittacosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('dakotaraptor', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('carcharodontosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('giraffatitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('tupandactylus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('rugops', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('ouranosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('deltadromeus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('patagotitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('dreadnoughtus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('hatzegopteryx', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('borealopelta', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('zuul', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('sauropelta', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('biomasa', 'BIOMASA', 'COMUN', 7, 4, false),
  ('araucarias', 'BIOMASA', 'COMUN', 3, 4, false),
  ('ginkgos', 'BIOMASA', 'COMUN', 3, 4, false),
  ('cicadas', 'BIOMASA', 'COMUN', 3, 4, false),
  ('equisetos', 'BIOMASA', 'COMUN', 3, 4, false),
  ('galeria', 'BIOMASA', 'COMUN', 3, 4, false),
  ('helechal', 'BIOMASA', 'COMUN', 3, 4, false),
  ('vega', 'BIOMASA', 'EPICO', 2, 35, false),
  ('humedal', 'BIOMASA', 'EPICO', 2, 35, false),
  ('manantial', 'BIOMASA', 'LEGENDARIO', 1, 100, false),
  ('jefe_saurophaganax', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_barosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_supersaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_hesperosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_harpactognathus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true)
on conflict (card_id) do update set
  tipo = excluded.tipo, rareza = excluded.rareza,
  copias_max = excluded.copias_max, valor_fusion = excluded.valor_fusion,
  es_jefe = excluded.es_jefe;

insert into public.catalogo_inicial (card_id, copias) values
  ('dryosaurus', 2),
  ('ceratosaurus', 2),
  ('stegosaurus', 1),
  ('kentrosaurus', 2),
  ('velociraptor', 2),
  ('allosaurus', 3),
  ('amargasaurus', 2),
  ('iguanodon', 3),
  ('pachycephalosaurus', 2),
  ('lokiceratops', 1),
  ('brachylophosaurus', 1),
  ('diplodocus', 1),
  ('apatosaurus', 2),
  ('tyrannotitan', 1),
  ('suchomimus', 1),
  ('deltadromeus', 1),
  ('monolophosaurus', 1),
  ('gregarismo', 2),
  ('trampa', 2),
  ('rebrote', 2),
  ('nido', 2),
  ('sabana_helechos', 2),
  ('insectos', 2),
  ('fractura', 2),
  ('gastrolitos', 1),
  ('crecimiento_acelerado', 1),
  ('sabana', 1),
  ('canal_trenzado', 1),
  ('biomasa', 5),
  ('araucarias', 2),
  ('cicadas', 2)
on conflict (card_id) do update set copias = excluded.copias;

delete from public.catalogo_inicial where card_id not in (
  'dryosaurus',
  'ceratosaurus',
  'stegosaurus',
  'kentrosaurus',
  'velociraptor',
  'allosaurus',
  'amargasaurus',
  'iguanodon',
  'pachycephalosaurus',
  'lokiceratops',
  'brachylophosaurus',
  'diplodocus',
  'apatosaurus',
  'tyrannotitan',
  'suchomimus',
  'deltadromeus',
  'monolophosaurus',
  'gregarismo',
  'trampa',
  'rebrote',
  'nido',
  'sabana_helechos',
  'insectos',
  'fractura',
  'gastrolitos',
  'crecimiento_acelerado',
  'sabana',
  'canal_trenzado',
  'biomasa',
  'araucarias',
  'cicadas'
);

insert into public.catalogo_iniciales (mazo, nombre, card_id, copias) values
  ('teropodos', 'Cazadores', 'ornitholestes', 3),
  ('teropodos', 'Cazadores', 'ceratosaurus', 3),
  ('teropodos', 'Cazadores', 'dromaeosaurus', 3),
  ('teropodos', 'Cazadores', 'velociraptor', 3),
  ('teropodos', 'Cazadores', 'therizinosaurus', 2),
  ('teropodos', 'Cazadores', 'ojoraptorsaurus', 2),
  ('teropodos', 'Cazadores', 'sanjuansaurus', 3),
  ('teropodos', 'Cazadores', 'allosaurus', 3),
  ('teropodos', 'Cazadores', 'riparovenator', 2),
  ('teropodos', 'Cazadores', 'carnotaurus', 2),
  ('teropodos', 'Cazadores', 'torvosaurus', 1),
  ('teropodos', 'Cazadores', 'tyrannotitan', 1),
  ('teropodos', 'Cazadores', 'gregarismo', 2),
  ('teropodos', 'Cazadores', 'trampa', 2),
  ('teropodos', 'Cazadores', 'rebrote', 2),
  ('teropodos', 'Cazadores', 'nido', 2),
  ('teropodos', 'Cazadores', 'sabana_helechos', 2),
  ('teropodos', 'Cazadores', 'insectos', 2),
  ('teropodos', 'Cazadores', 'fractura', 2),
  ('teropodos', 'Cazadores', 'gastrolitos', 1),
  ('teropodos', 'Cazadores', 'crecimiento_acelerado', 1),
  ('teropodos', 'Cazadores', 'sabana', 1),
  ('teropodos', 'Cazadores', 'canal_trenzado', 1),
  ('teropodos', 'Cazadores', 'biomasa', 5),
  ('teropodos', 'Cazadores', 'araucarias', 2),
  ('teropodos', 'Cazadores', 'cicadas', 2),
  ('sauropodos', 'Gigantes', 'plateosauravus', 3),
  ('sauropodos', 'Gigantes', 'athenar', 3),
  ('sauropodos', 'Gigantes', 'amargasaurus', 3),
  ('sauropodos', 'Gigantes', 'diplodocus', 3),
  ('sauropodos', 'Gigantes', 'apatosaurus', 2),
  ('sauropodos', 'Gigantes', 'camarasaurus', 2),
  ('sauropodos', 'Gigantes', 'mamenchisaurus', 3),
  ('sauropodos', 'Gigantes', 'atlasaurus', 1),
  ('sauropodos', 'Gigantes', 'brachiosaurus', 1),
  ('sauropodos', 'Gigantes', 'ceratosaurus', 3),
  ('sauropodos', 'Gigantes', 'velociraptor', 3),
  ('sauropodos', 'Gigantes', 'ornitholestes', 1),
  ('sauropodos', 'Gigantes', 'gregarismo', 2),
  ('sauropodos', 'Gigantes', 'trampa', 2),
  ('sauropodos', 'Gigantes', 'rebrote', 2),
  ('sauropodos', 'Gigantes', 'nido', 2),
  ('sauropodos', 'Gigantes', 'sabana_helechos', 2),
  ('sauropodos', 'Gigantes', 'insectos', 2),
  ('sauropodos', 'Gigantes', 'fractura', 2),
  ('sauropodos', 'Gigantes', 'gastrolitos', 1),
  ('sauropodos', 'Gigantes', 'crecimiento_acelerado', 1),
  ('sauropodos', 'Gigantes', 'sabana', 1),
  ('sauropodos', 'Gigantes', 'canal_trenzado', 1),
  ('sauropodos', 'Gigantes', 'biomasa', 5),
  ('sauropodos', 'Gigantes', 'araucarias', 2),
  ('sauropodos', 'Gigantes', 'cicadas', 2),
  ('ornitopodos', 'Manadas', 'dryosaurus', 3),
  ('ornitopodos', 'Manadas', 'shuangmiaosaurus', 3),
  ('ornitopodos', 'Manadas', 'iguanodon', 3),
  ('ornitopodos', 'Manadas', 'brachylophosaurus', 3),
  ('ornitopodos', 'Manadas', 'parasaurolophus', 3),
  ('ornitopodos', 'Manadas', 'rhinorex', 2),
  ('ornitopodos', 'Manadas', 'maiasaura', 1),
  ('ornitopodos', 'Manadas', 'edmontosaurus', 1),
  ('ornitopodos', 'Manadas', 'pachycephalosaurus', 2),
  ('ornitopodos', 'Manadas', 'allosaurus', 1),
  ('ornitopodos', 'Manadas', 'ornitholestes', 1),
  ('ornitopodos', 'Manadas', 'velociraptor', 3),
  ('ornitopodos', 'Manadas', 'ceratosaurus', 2),
  ('ornitopodos', 'Manadas', 'gregarismo', 2),
  ('ornitopodos', 'Manadas', 'trampa', 2),
  ('ornitopodos', 'Manadas', 'rebrote', 2),
  ('ornitopodos', 'Manadas', 'nido', 2),
  ('ornitopodos', 'Manadas', 'sabana_helechos', 2),
  ('ornitopodos', 'Manadas', 'insectos', 2),
  ('ornitopodos', 'Manadas', 'fractura', 2),
  ('ornitopodos', 'Manadas', 'gastrolitos', 1),
  ('ornitopodos', 'Manadas', 'crecimiento_acelerado', 1),
  ('ornitopodos', 'Manadas', 'sabana', 1),
  ('ornitopodos', 'Manadas', 'canal_trenzado', 1),
  ('ornitopodos', 'Manadas', 'biomasa', 5),
  ('ornitopodos', 'Manadas', 'araucarias', 2),
  ('ornitopodos', 'Manadas', 'cicadas', 2)
on conflict (mazo, card_id) do update set nombre = excluded.nombre, copias = excluded.copias;

delete from public.catalogo_iniciales where (mazo, card_id) not in (values
  ('teropodos', 'ornitholestes'),
  ('teropodos', 'ceratosaurus'),
  ('teropodos', 'dromaeosaurus'),
  ('teropodos', 'velociraptor'),
  ('teropodos', 'therizinosaurus'),
  ('teropodos', 'ojoraptorsaurus'),
  ('teropodos', 'sanjuansaurus'),
  ('teropodos', 'allosaurus'),
  ('teropodos', 'riparovenator'),
  ('teropodos', 'carnotaurus'),
  ('teropodos', 'torvosaurus'),
  ('teropodos', 'tyrannotitan'),
  ('teropodos', 'gregarismo'),
  ('teropodos', 'trampa'),
  ('teropodos', 'rebrote'),
  ('teropodos', 'nido'),
  ('teropodos', 'sabana_helechos'),
  ('teropodos', 'insectos'),
  ('teropodos', 'fractura'),
  ('teropodos', 'gastrolitos'),
  ('teropodos', 'crecimiento_acelerado'),
  ('teropodos', 'sabana'),
  ('teropodos', 'canal_trenzado'),
  ('teropodos', 'biomasa'),
  ('teropodos', 'araucarias'),
  ('teropodos', 'cicadas'),
  ('sauropodos', 'plateosauravus'),
  ('sauropodos', 'athenar'),
  ('sauropodos', 'amargasaurus'),
  ('sauropodos', 'diplodocus'),
  ('sauropodos', 'apatosaurus'),
  ('sauropodos', 'camarasaurus'),
  ('sauropodos', 'mamenchisaurus'),
  ('sauropodos', 'atlasaurus'),
  ('sauropodos', 'brachiosaurus'),
  ('sauropodos', 'ceratosaurus'),
  ('sauropodos', 'velociraptor'),
  ('sauropodos', 'ornitholestes'),
  ('sauropodos', 'gregarismo'),
  ('sauropodos', 'trampa'),
  ('sauropodos', 'rebrote'),
  ('sauropodos', 'nido'),
  ('sauropodos', 'sabana_helechos'),
  ('sauropodos', 'insectos'),
  ('sauropodos', 'fractura'),
  ('sauropodos', 'gastrolitos'),
  ('sauropodos', 'crecimiento_acelerado'),
  ('sauropodos', 'sabana'),
  ('sauropodos', 'canal_trenzado'),
  ('sauropodos', 'biomasa'),
  ('sauropodos', 'araucarias'),
  ('sauropodos', 'cicadas'),
  ('ornitopodos', 'dryosaurus'),
  ('ornitopodos', 'shuangmiaosaurus'),
  ('ornitopodos', 'iguanodon'),
  ('ornitopodos', 'brachylophosaurus'),
  ('ornitopodos', 'parasaurolophus'),
  ('ornitopodos', 'rhinorex'),
  ('ornitopodos', 'maiasaura'),
  ('ornitopodos', 'edmontosaurus'),
  ('ornitopodos', 'pachycephalosaurus'),
  ('ornitopodos', 'allosaurus'),
  ('ornitopodos', 'ornitholestes'),
  ('ornitopodos', 'velociraptor'),
  ('ornitopodos', 'ceratosaurus'),
  ('ornitopodos', 'gregarismo'),
  ('ornitopodos', 'trampa'),
  ('ornitopodos', 'rebrote'),
  ('ornitopodos', 'nido'),
  ('ornitopodos', 'sabana_helechos'),
  ('ornitopodos', 'insectos'),
  ('ornitopodos', 'fractura'),
  ('ornitopodos', 'gastrolitos'),
  ('ornitopodos', 'crecimiento_acelerado'),
  ('ornitopodos', 'sabana'),
  ('ornitopodos', 'canal_trenzado'),
  ('ornitopodos', 'biomasa'),
  ('ornitopodos', 'araucarias'),
  ('ornitopodos', 'cicadas')
);

insert into public.catalogo_cosmeticos (id, tipo, precio, por_defecto, exclusivo) values
  ('dorso_clasico', 'DORSO', 0, true, false),
  ('dorso_ambar', 'DORSO', 300, false, false),
  ('dorso_obsidiana', 'DORSO', 300, false, false),
  ('dorso_morrison', 'DORSO', 300, false, false),
  ('dorso_hell_creek', 'DORSO', 300, false, false),
  ('dorso_kem_kem', 'DORSO', 300, false, false),
  ('dorso_volcan', 'DORSO', 300, false, false),
  ('dorso_cazador', 'DORSO', 0, false, true),
  ('tapete_clasico', 'TAPETE', 0, true, false),
  ('tapete_ambar', 'TAPETE', 500, false, false),
  ('tapete_obsidiana', 'TAPETE', 500, false, false),
  ('tapete_morrison', 'TAPETE', 500, false, false),
  ('tapete_volcan', 'TAPETE', 500, false, false),
  ('tapete_hell_creek', 'TAPETE', 500, false, false),
  ('tapete_kem_kem', 'TAPETE', 500, false, false),
  ('tapete_solnhofen', 'TAPETE', 500, false, false),
  ('tapete_excavacion', 'TAPETE', 500, false, false),
  ('estandarte_clasico', 'ESTANDARTE', 0, true, false),
  ('estandarte_ambar', 'ESTANDARTE', 400, false, false),
  ('estandarte_obsidiana', 'ESTANDARTE', 400, false, false),
  ('estandarte_fosil', 'ESTANDARTE', 400, false, false),
  ('estandarte_volcan', 'ESTANDARTE', 400, false, false),
  ('estandarte_helecho', 'ESTANDARTE', 400, false, false),
  ('estandarte_campeon', 'ESTANDARTE', 0, false, true),
  ('retrato_paleontologa', 'RETRATO', 0, true, false),
  ('retrato_buscador', 'RETRATO', 0, false, false),
  ('retrato_amonite', 'RETRATO', 350, false, false),
  ('retrato_huevo', 'RETRATO', 350, false, false),
  ('retrato_placas', 'RETRATO', 350, false, false),
  ('retrato_cientifico', 'RETRATO', 350, false, false),
  ('retrato_cientifica', 'RETRATO', 350, false, false),
  ('retrato_cazador', 'RETRATO', 350, false, false),
  ('retrato_trex', 'RETRATO', 350, false, false),
  ('retrato_saurophaganax', 'RETRATO', 0, false, true),
  ('retrato_barosaurus', 'RETRATO', 0, false, true),
  ('retrato_supersaurus', 'RETRATO', 0, false, true),
  ('retrato_hesperosaurus', 'RETRATO', 0, false, true),
  ('retrato_harpactognathus', 'RETRATO', 0, false, true),
  ('titulo_ninguno', 'TITULO', 0, true, false),
  ('titulo_duelista', 'TITULO', 0, false, true),
  ('titulo_asaltante', 'TITULO', 0, false, true),
  ('titulo_cazador', 'TITULO', 0, false, true),
  ('titulo_campeon', 'TITULO', 0, false, true)
on conflict (id) do update set tipo = excluded.tipo, precio = excluded.precio,
  por_defecto = excluded.por_defecto, exclusivo = excluded.exclusivo;

delete from public.catalogo_cosmeticos where id not in (
  'dorso_clasico',
  'dorso_ambar',
  'dorso_obsidiana',
  'dorso_morrison',
  'dorso_hell_creek',
  'dorso_kem_kem',
  'dorso_volcan',
  'dorso_cazador',
  'tapete_clasico',
  'tapete_ambar',
  'tapete_obsidiana',
  'tapete_morrison',
  'tapete_volcan',
  'tapete_hell_creek',
  'tapete_kem_kem',
  'tapete_solnhofen',
  'tapete_excavacion',
  'estandarte_clasico',
  'estandarte_ambar',
  'estandarte_obsidiana',
  'estandarte_fosil',
  'estandarte_volcan',
  'estandarte_helecho',
  'estandarte_campeon',
  'retrato_paleontologa',
  'retrato_buscador',
  'retrato_amonite',
  'retrato_huevo',
  'retrato_placas',
  'retrato_cientifico',
  'retrato_cientifica',
  'retrato_cazador',
  'retrato_trex',
  'retrato_saurophaganax',
  'retrato_barosaurus',
  'retrato_supersaurus',
  'retrato_hesperosaurus',
  'retrato_harpactognathus',
  'titulo_ninguno',
  'titulo_duelista',
  'titulo_asaltante',
  'titulo_cazador',
  'titulo_campeon'
);

insert into public.catalogo_crafteo (rareza, fundir, crear) values
  ('COMUN', 10, 80),
  ('RARO', 30, 200),
  ('EPICO', 150, 500),
  ('LEGENDARIO', 400, 1600)
on conflict (rareza) do update set fundir = excluded.fundir, crear = excluded.crear;

insert into public.catalogo_torneos (id, nombre, orden, copias_max) values
  ('cada_hueso_uno', 'Cada hueso uno', 0, 1),
  ('sin_colmillos', 'Sin colmillos', 1, null),
  ('cielo_y_mar', 'El cielo y el mar', 2, null),
  ('el_muro', 'El muro', 3, null),
  ('sin_trampas', 'Sin trampas', 4, null),
  ('a_dentelladas', 'A dentelladas', 5, null),
  ('los_pequenos', 'Los pequeños', 6, null)
on conflict (id) do update set nombre = excluded.nombre,
  orden = excluded.orden, copias_max = excluded.copias_max;

insert into public.catalogo_torneo_cartas (torneo, card_id) values
  ('cada_hueso_uno', 'dryosaurus'),
  ('cada_hueso_uno', 'ornitholestes'),
  ('cada_hueso_uno', 'ceratosaurus'),
  ('cada_hueso_uno', 'stegosaurus'),
  ('cada_hueso_uno', 'allosaurus'),
  ('cada_hueso_uno', 'camarasaurus'),
  ('cada_hueso_uno', 'diplodocus'),
  ('cada_hueso_uno', 'apatosaurus'),
  ('cada_hueso_uno', 'torvosaurus'),
  ('cada_hueso_uno', 'nodosaurus'),
  ('cada_hueso_uno', 'riparovenator'),
  ('cada_hueso_uno', 'lokiceratops'),
  ('cada_hueso_uno', 'brachylophosaurus'),
  ('cada_hueso_uno', 'tyrannotitan'),
  ('cada_hueso_uno', 'huaxiadraco'),
  ('cada_hueso_uno', 'gregarismo'),
  ('cada_hueso_uno', 'gastrolitos'),
  ('cada_hueso_uno', 'crecimiento_acelerado'),
  ('cada_hueso_uno', 'neumaticidad'),
  ('cada_hueso_uno', 'fractura'),
  ('cada_hueso_uno', 'competencia'),
  ('cada_hueso_uno', 'trampa'),
  ('cada_hueso_uno', 'mortandad'),
  ('cada_hueso_uno', 'sabana_helechos'),
  ('cada_hueso_uno', 'inundacion'),
  ('cada_hueso_uno', 'canal_trenzado'),
  ('cada_hueso_uno', 'bosque_ribereno'),
  ('cada_hueso_uno', 'deriva_arida'),
  ('cada_hueso_uno', 'nido'),
  ('cada_hueso_uno', 'tormenta_polvo'),
  ('cada_hueso_uno', 'avenida_lodo'),
  ('cada_hueso_uno', 'enterramiento'),
  ('cada_hueso_uno', 'cauce_abandonado'),
  ('cada_hueso_uno', 'barrera_troncos'),
  ('cada_hueso_uno', 'ceniza'),
  ('cada_hueso_uno', 'sedimento'),
  ('cada_hueso_uno', 'osario'),
  ('cada_hueso_uno', 'carroneros'),
  ('cada_hueso_uno', 'oleada'),
  ('cada_hueso_uno', 'estampida'),
  ('cada_hueso_uno', 'migracion'),
  ('cada_hueso_uno', 'crecida_delta'),
  ('cada_hueso_uno', 'cantera'),
  ('cada_hueso_uno', 'incendio'),
  ('cada_hueso_uno', 'acuifero'),
  ('cada_hueso_uno', 'rebrote'),
  ('cada_hueso_uno', 'carrona'),
  ('cada_hueso_uno', 'lago'),
  ('cada_hueso_uno', 'insectos'),
  ('cada_hueso_uno', 'manada_paso'),
  ('cada_hueso_uno', 'frutos'),
  ('cada_hueso_uno', 'llanura'),
  ('cada_hueso_uno', 'canal'),
  ('cada_hueso_uno', 'bosque'),
  ('cada_hueso_uno', 'aridez'),
  ('cada_hueso_uno', 'sabana'),
  ('cada_hueso_uno', 'plesiopleurodon'),
  ('cada_hueso_uno', 'ojoraptorsaurus'),
  ('cada_hueso_uno', 'dromaeosaurus'),
  ('cada_hueso_uno', 'athenar'),
  ('cada_hueso_uno', 'sanjuansaurus'),
  ('cada_hueso_uno', 'suchomimus'),
  ('cada_hueso_uno', 'eosinopteryx'),
  ('cada_hueso_uno', 'troodon'),
  ('cada_hueso_uno', 'carnotaurus'),
  ('cada_hueso_uno', 'spinosaurus'),
  ('cada_hueso_uno', 'mosasaurus'),
  ('cada_hueso_uno', 'halszkaraptor'),
  ('cada_hueso_uno', 'tongtianlong'),
  ('cada_hueso_uno', 'scanisaurus'),
  ('cada_hueso_uno', 'monolophosaurus'),
  ('cada_hueso_uno', 'invictarx'),
  ('cada_hueso_uno', 'medusaceratops'),
  ('cada_hueso_uno', 'platyceratops'),
  ('cada_hueso_uno', 'loricatosaurus'),
  ('cada_hueso_uno', 'therizinosaurus'),
  ('cada_hueso_uno', 'alaskacephale'),
  ('cada_hueso_uno', 'titanoceratops'),
  ('cada_hueso_uno', 'atlasaurus'),
  ('cada_hueso_uno', 'stegoceras'),
  ('cada_hueso_uno', 'maiasaura'),
  ('cada_hueso_uno', 'edmontosaurus'),
  ('cada_hueso_uno', 'plateosauravus'),
  ('cada_hueso_uno', 'gargoyleosaurus'),
  ('cada_hueso_uno', 'wendiceratops'),
  ('cada_hueso_uno', 'antarctosaurus'),
  ('cada_hueso_uno', 'liaoceratops'),
  ('cada_hueso_uno', 'rhinorex'),
  ('cada_hueso_uno', 'bienosaurus'),
  ('cada_hueso_uno', 'shuangmiaosaurus'),
  ('cada_hueso_uno', 'chasmosaurus'),
  ('cada_hueso_uno', 'tyrannosaurus'),
  ('cada_hueso_uno', 'velociraptor'),
  ('cada_hueso_uno', 'brachiosaurus'),
  ('cada_hueso_uno', 'argentinosaurus'),
  ('cada_hueso_uno', 'mamenchisaurus'),
  ('cada_hueso_uno', 'amargasaurus'),
  ('cada_hueso_uno', 'ankylosaurus'),
  ('cada_hueso_uno', 'kentrosaurus'),
  ('cada_hueso_uno', 'euoplocephalus'),
  ('cada_hueso_uno', 'triceratops'),
  ('cada_hueso_uno', 'pachycephalosaurus'),
  ('cada_hueso_uno', 'iguanodon'),
  ('cada_hueso_uno', 'parasaurolophus'),
  ('cada_hueso_uno', 'pteranodon'),
  ('cada_hueso_uno', 'quetzalcoatlus'),
  ('cada_hueso_uno', 'elasmosaurus'),
  ('cada_hueso_uno', 'gallimimus'),
  ('cada_hueso_uno', 'thescelosaurus'),
  ('cada_hueso_uno', 'deinocheirus'),
  ('cada_hueso_uno', 'anzu'),
  ('cada_hueso_uno', 'nigersaurus'),
  ('cada_hueso_uno', 'shuvuuia'),
  ('cada_hueso_uno', 'saurolophus'),
  ('cada_hueso_uno', 'tarbosaurus'),
  ('cada_hueso_uno', 'psittacosaurus'),
  ('cada_hueso_uno', 'dakotaraptor'),
  ('cada_hueso_uno', 'carcharodontosaurus'),
  ('cada_hueso_uno', 'giraffatitan'),
  ('cada_hueso_uno', 'tupandactylus'),
  ('cada_hueso_uno', 'rugops'),
  ('cada_hueso_uno', 'ouranosaurus'),
  ('cada_hueso_uno', 'deltadromeus'),
  ('cada_hueso_uno', 'patagotitan'),
  ('cada_hueso_uno', 'dreadnoughtus'),
  ('cada_hueso_uno', 'hatzegopteryx'),
  ('cada_hueso_uno', 'borealopelta'),
  ('cada_hueso_uno', 'zuul'),
  ('cada_hueso_uno', 'sauropelta'),
  ('cada_hueso_uno', 'biomasa'),
  ('cada_hueso_uno', 'araucarias'),
  ('cada_hueso_uno', 'ginkgos'),
  ('cada_hueso_uno', 'cicadas'),
  ('cada_hueso_uno', 'equisetos'),
  ('cada_hueso_uno', 'galeria'),
  ('cada_hueso_uno', 'helechal'),
  ('cada_hueso_uno', 'vega'),
  ('cada_hueso_uno', 'humedal'),
  ('cada_hueso_uno', 'manantial'),
  ('sin_colmillos', 'dryosaurus'),
  ('sin_colmillos', 'ornitholestes'),
  ('sin_colmillos', 'ceratosaurus'),
  ('sin_colmillos', 'stegosaurus'),
  ('sin_colmillos', 'diplodocus'),
  ('sin_colmillos', 'brachylophosaurus'),
  ('sin_colmillos', 'huaxiadraco'),
  ('sin_colmillos', 'gregarismo'),
  ('sin_colmillos', 'gastrolitos'),
  ('sin_colmillos', 'neumaticidad'),
  ('sin_colmillos', 'fractura'),
  ('sin_colmillos', 'trampa'),
  ('sin_colmillos', 'sabana_helechos'),
  ('sin_colmillos', 'inundacion'),
  ('sin_colmillos', 'canal_trenzado'),
  ('sin_colmillos', 'bosque_ribereno'),
  ('sin_colmillos', 'deriva_arida'),
  ('sin_colmillos', 'nido'),
  ('sin_colmillos', 'tormenta_polvo'),
  ('sin_colmillos', 'avenida_lodo'),
  ('sin_colmillos', 'enterramiento'),
  ('sin_colmillos', 'cauce_abandonado'),
  ('sin_colmillos', 'barrera_troncos'),
  ('sin_colmillos', 'ceniza'),
  ('sin_colmillos', 'sedimento'),
  ('sin_colmillos', 'osario'),
  ('sin_colmillos', 'carroneros'),
  ('sin_colmillos', 'oleada'),
  ('sin_colmillos', 'estampida'),
  ('sin_colmillos', 'migracion'),
  ('sin_colmillos', 'crecida_delta'),
  ('sin_colmillos', 'cantera'),
  ('sin_colmillos', 'incendio'),
  ('sin_colmillos', 'rebrote'),
  ('sin_colmillos', 'lago'),
  ('sin_colmillos', 'insectos'),
  ('sin_colmillos', 'manada_paso'),
  ('sin_colmillos', 'frutos'),
  ('sin_colmillos', 'llanura'),
  ('sin_colmillos', 'sabana'),
  ('sin_colmillos', 'ojoraptorsaurus'),
  ('sin_colmillos', 'dromaeosaurus'),
  ('sin_colmillos', 'athenar'),
  ('sin_colmillos', 'sanjuansaurus'),
  ('sin_colmillos', 'eosinopteryx'),
  ('sin_colmillos', 'troodon'),
  ('sin_colmillos', 'halszkaraptor'),
  ('sin_colmillos', 'tongtianlong'),
  ('sin_colmillos', 'platyceratops'),
  ('sin_colmillos', 'alaskacephale'),
  ('sin_colmillos', 'stegoceras'),
  ('sin_colmillos', 'plateosauravus'),
  ('sin_colmillos', 'gargoyleosaurus'),
  ('sin_colmillos', 'liaoceratops'),
  ('sin_colmillos', 'bienosaurus'),
  ('sin_colmillos', 'shuangmiaosaurus'),
  ('sin_colmillos', 'chasmosaurus'),
  ('sin_colmillos', 'velociraptor'),
  ('sin_colmillos', 'amargasaurus'),
  ('sin_colmillos', 'kentrosaurus'),
  ('sin_colmillos', 'pachycephalosaurus'),
  ('sin_colmillos', 'iguanodon'),
  ('sin_colmillos', 'pteranodon'),
  ('sin_colmillos', 'gallimimus'),
  ('sin_colmillos', 'thescelosaurus'),
  ('sin_colmillos', 'anzu'),
  ('sin_colmillos', 'shuvuuia'),
  ('sin_colmillos', 'psittacosaurus'),
  ('sin_colmillos', 'rugops'),
  ('sin_colmillos', 'ouranosaurus'),
  ('sin_colmillos', 'zuul'),
  ('sin_colmillos', 'biomasa'),
  ('sin_colmillos', 'araucarias'),
  ('sin_colmillos', 'ginkgos'),
  ('sin_colmillos', 'cicadas'),
  ('sin_colmillos', 'equisetos'),
  ('sin_colmillos', 'galeria'),
  ('sin_colmillos', 'helechal'),
  ('sin_colmillos', 'vega'),
  ('sin_colmillos', 'humedal'),
  ('cielo_y_mar', 'huaxiadraco'),
  ('cielo_y_mar', 'gregarismo'),
  ('cielo_y_mar', 'gastrolitos'),
  ('cielo_y_mar', 'crecimiento_acelerado'),
  ('cielo_y_mar', 'neumaticidad'),
  ('cielo_y_mar', 'fractura'),
  ('cielo_y_mar', 'competencia'),
  ('cielo_y_mar', 'trampa'),
  ('cielo_y_mar', 'mortandad'),
  ('cielo_y_mar', 'sabana_helechos'),
  ('cielo_y_mar', 'inundacion'),
  ('cielo_y_mar', 'canal_trenzado'),
  ('cielo_y_mar', 'bosque_ribereno'),
  ('cielo_y_mar', 'deriva_arida'),
  ('cielo_y_mar', 'nido'),
  ('cielo_y_mar', 'tormenta_polvo'),
  ('cielo_y_mar', 'avenida_lodo'),
  ('cielo_y_mar', 'enterramiento'),
  ('cielo_y_mar', 'cauce_abandonado'),
  ('cielo_y_mar', 'barrera_troncos'),
  ('cielo_y_mar', 'ceniza'),
  ('cielo_y_mar', 'sedimento'),
  ('cielo_y_mar', 'osario'),
  ('cielo_y_mar', 'carroneros'),
  ('cielo_y_mar', 'oleada'),
  ('cielo_y_mar', 'estampida'),
  ('cielo_y_mar', 'migracion'),
  ('cielo_y_mar', 'crecida_delta'),
  ('cielo_y_mar', 'cantera'),
  ('cielo_y_mar', 'incendio'),
  ('cielo_y_mar', 'acuifero'),
  ('cielo_y_mar', 'rebrote'),
  ('cielo_y_mar', 'carrona'),
  ('cielo_y_mar', 'lago'),
  ('cielo_y_mar', 'insectos'),
  ('cielo_y_mar', 'manada_paso'),
  ('cielo_y_mar', 'frutos'),
  ('cielo_y_mar', 'llanura'),
  ('cielo_y_mar', 'canal'),
  ('cielo_y_mar', 'bosque'),
  ('cielo_y_mar', 'aridez'),
  ('cielo_y_mar', 'sabana'),
  ('cielo_y_mar', 'plesiopleurodon'),
  ('cielo_y_mar', 'mosasaurus'),
  ('cielo_y_mar', 'scanisaurus'),
  ('cielo_y_mar', 'pteranodon'),
  ('cielo_y_mar', 'quetzalcoatlus'),
  ('cielo_y_mar', 'elasmosaurus'),
  ('cielo_y_mar', 'tupandactylus'),
  ('cielo_y_mar', 'hatzegopteryx'),
  ('cielo_y_mar', 'biomasa'),
  ('cielo_y_mar', 'araucarias'),
  ('cielo_y_mar', 'ginkgos'),
  ('cielo_y_mar', 'cicadas'),
  ('cielo_y_mar', 'equisetos'),
  ('cielo_y_mar', 'galeria'),
  ('cielo_y_mar', 'helechal'),
  ('cielo_y_mar', 'vega'),
  ('cielo_y_mar', 'humedal'),
  ('cielo_y_mar', 'manantial'),
  ('el_muro', 'stegosaurus'),
  ('el_muro', 'camarasaurus'),
  ('el_muro', 'diplodocus'),
  ('el_muro', 'apatosaurus'),
  ('el_muro', 'nodosaurus'),
  ('el_muro', 'gregarismo'),
  ('el_muro', 'gastrolitos'),
  ('el_muro', 'crecimiento_acelerado'),
  ('el_muro', 'neumaticidad'),
  ('el_muro', 'fractura'),
  ('el_muro', 'competencia'),
  ('el_muro', 'trampa'),
  ('el_muro', 'mortandad'),
  ('el_muro', 'sabana_helechos'),
  ('el_muro', 'inundacion'),
  ('el_muro', 'canal_trenzado'),
  ('el_muro', 'bosque_ribereno'),
  ('el_muro', 'deriva_arida'),
  ('el_muro', 'nido'),
  ('el_muro', 'tormenta_polvo'),
  ('el_muro', 'avenida_lodo'),
  ('el_muro', 'enterramiento'),
  ('el_muro', 'cauce_abandonado'),
  ('el_muro', 'barrera_troncos'),
  ('el_muro', 'ceniza'),
  ('el_muro', 'sedimento'),
  ('el_muro', 'osario'),
  ('el_muro', 'carroneros'),
  ('el_muro', 'oleada'),
  ('el_muro', 'estampida'),
  ('el_muro', 'migracion'),
  ('el_muro', 'crecida_delta'),
  ('el_muro', 'cantera'),
  ('el_muro', 'incendio'),
  ('el_muro', 'acuifero'),
  ('el_muro', 'rebrote'),
  ('el_muro', 'carrona'),
  ('el_muro', 'lago'),
  ('el_muro', 'insectos'),
  ('el_muro', 'manada_paso'),
  ('el_muro', 'frutos'),
  ('el_muro', 'llanura'),
  ('el_muro', 'canal'),
  ('el_muro', 'bosque'),
  ('el_muro', 'aridez'),
  ('el_muro', 'sabana'),
  ('el_muro', 'athenar'),
  ('el_muro', 'invictarx'),
  ('el_muro', 'loricatosaurus'),
  ('el_muro', 'atlasaurus'),
  ('el_muro', 'plateosauravus'),
  ('el_muro', 'gargoyleosaurus'),
  ('el_muro', 'antarctosaurus'),
  ('el_muro', 'bienosaurus'),
  ('el_muro', 'brachiosaurus'),
  ('el_muro', 'argentinosaurus'),
  ('el_muro', 'mamenchisaurus'),
  ('el_muro', 'amargasaurus'),
  ('el_muro', 'ankylosaurus'),
  ('el_muro', 'kentrosaurus'),
  ('el_muro', 'euoplocephalus'),
  ('el_muro', 'nigersaurus'),
  ('el_muro', 'giraffatitan'),
  ('el_muro', 'patagotitan'),
  ('el_muro', 'dreadnoughtus'),
  ('el_muro', 'borealopelta'),
  ('el_muro', 'zuul'),
  ('el_muro', 'sauropelta'),
  ('el_muro', 'biomasa'),
  ('el_muro', 'araucarias'),
  ('el_muro', 'ginkgos'),
  ('el_muro', 'cicadas'),
  ('el_muro', 'equisetos'),
  ('el_muro', 'galeria'),
  ('el_muro', 'helechal'),
  ('el_muro', 'vega'),
  ('el_muro', 'humedal'),
  ('el_muro', 'manantial'),
  ('sin_trampas', 'dryosaurus'),
  ('sin_trampas', 'ornitholestes'),
  ('sin_trampas', 'ceratosaurus'),
  ('sin_trampas', 'stegosaurus'),
  ('sin_trampas', 'allosaurus'),
  ('sin_trampas', 'camarasaurus'),
  ('sin_trampas', 'diplodocus'),
  ('sin_trampas', 'apatosaurus'),
  ('sin_trampas', 'torvosaurus'),
  ('sin_trampas', 'nodosaurus'),
  ('sin_trampas', 'riparovenator'),
  ('sin_trampas', 'lokiceratops'),
  ('sin_trampas', 'brachylophosaurus'),
  ('sin_trampas', 'tyrannotitan'),
  ('sin_trampas', 'huaxiadraco'),
  ('sin_trampas', 'cantera'),
  ('sin_trampas', 'rebrote'),
  ('sin_trampas', 'carrona'),
  ('sin_trampas', 'lago'),
  ('sin_trampas', 'insectos'),
  ('sin_trampas', 'manada_paso'),
  ('sin_trampas', 'frutos'),
  ('sin_trampas', 'llanura'),
  ('sin_trampas', 'canal'),
  ('sin_trampas', 'bosque'),
  ('sin_trampas', 'aridez'),
  ('sin_trampas', 'sabana'),
  ('sin_trampas', 'plesiopleurodon'),
  ('sin_trampas', 'ojoraptorsaurus'),
  ('sin_trampas', 'dromaeosaurus'),
  ('sin_trampas', 'athenar'),
  ('sin_trampas', 'sanjuansaurus'),
  ('sin_trampas', 'suchomimus'),
  ('sin_trampas', 'eosinopteryx'),
  ('sin_trampas', 'troodon'),
  ('sin_trampas', 'carnotaurus'),
  ('sin_trampas', 'spinosaurus'),
  ('sin_trampas', 'mosasaurus'),
  ('sin_trampas', 'halszkaraptor'),
  ('sin_trampas', 'tongtianlong'),
  ('sin_trampas', 'scanisaurus'),
  ('sin_trampas', 'monolophosaurus'),
  ('sin_trampas', 'invictarx'),
  ('sin_trampas', 'medusaceratops'),
  ('sin_trampas', 'platyceratops'),
  ('sin_trampas', 'loricatosaurus'),
  ('sin_trampas', 'therizinosaurus'),
  ('sin_trampas', 'alaskacephale'),
  ('sin_trampas', 'titanoceratops'),
  ('sin_trampas', 'atlasaurus'),
  ('sin_trampas', 'stegoceras'),
  ('sin_trampas', 'maiasaura'),
  ('sin_trampas', 'edmontosaurus'),
  ('sin_trampas', 'plateosauravus'),
  ('sin_trampas', 'gargoyleosaurus'),
  ('sin_trampas', 'wendiceratops'),
  ('sin_trampas', 'antarctosaurus'),
  ('sin_trampas', 'liaoceratops'),
  ('sin_trampas', 'rhinorex'),
  ('sin_trampas', 'bienosaurus'),
  ('sin_trampas', 'shuangmiaosaurus'),
  ('sin_trampas', 'chasmosaurus'),
  ('sin_trampas', 'tyrannosaurus'),
  ('sin_trampas', 'velociraptor'),
  ('sin_trampas', 'brachiosaurus'),
  ('sin_trampas', 'argentinosaurus'),
  ('sin_trampas', 'mamenchisaurus'),
  ('sin_trampas', 'amargasaurus'),
  ('sin_trampas', 'ankylosaurus'),
  ('sin_trampas', 'kentrosaurus'),
  ('sin_trampas', 'euoplocephalus'),
  ('sin_trampas', 'triceratops'),
  ('sin_trampas', 'pachycephalosaurus'),
  ('sin_trampas', 'iguanodon'),
  ('sin_trampas', 'parasaurolophus'),
  ('sin_trampas', 'pteranodon'),
  ('sin_trampas', 'quetzalcoatlus'),
  ('sin_trampas', 'elasmosaurus'),
  ('sin_trampas', 'gallimimus'),
  ('sin_trampas', 'thescelosaurus'),
  ('sin_trampas', 'deinocheirus'),
  ('sin_trampas', 'anzu'),
  ('sin_trampas', 'nigersaurus'),
  ('sin_trampas', 'shuvuuia'),
  ('sin_trampas', 'saurolophus'),
  ('sin_trampas', 'tarbosaurus'),
  ('sin_trampas', 'psittacosaurus'),
  ('sin_trampas', 'dakotaraptor'),
  ('sin_trampas', 'carcharodontosaurus'),
  ('sin_trampas', 'giraffatitan'),
  ('sin_trampas', 'tupandactylus'),
  ('sin_trampas', 'rugops'),
  ('sin_trampas', 'ouranosaurus'),
  ('sin_trampas', 'deltadromeus'),
  ('sin_trampas', 'patagotitan'),
  ('sin_trampas', 'dreadnoughtus'),
  ('sin_trampas', 'hatzegopteryx'),
  ('sin_trampas', 'borealopelta'),
  ('sin_trampas', 'zuul'),
  ('sin_trampas', 'sauropelta'),
  ('sin_trampas', 'biomasa'),
  ('sin_trampas', 'araucarias'),
  ('sin_trampas', 'ginkgos'),
  ('sin_trampas', 'cicadas'),
  ('sin_trampas', 'equisetos'),
  ('sin_trampas', 'galeria'),
  ('sin_trampas', 'helechal'),
  ('sin_trampas', 'vega'),
  ('sin_trampas', 'humedal'),
  ('sin_trampas', 'manantial'),
  ('a_dentelladas', 'dryosaurus'),
  ('a_dentelladas', 'ornitholestes'),
  ('a_dentelladas', 'ceratosaurus'),
  ('a_dentelladas', 'stegosaurus'),
  ('a_dentelladas', 'allosaurus'),
  ('a_dentelladas', 'camarasaurus'),
  ('a_dentelladas', 'diplodocus'),
  ('a_dentelladas', 'apatosaurus'),
  ('a_dentelladas', 'torvosaurus'),
  ('a_dentelladas', 'nodosaurus'),
  ('a_dentelladas', 'riparovenator'),
  ('a_dentelladas', 'lokiceratops'),
  ('a_dentelladas', 'brachylophosaurus'),
  ('a_dentelladas', 'tyrannotitan'),
  ('a_dentelladas', 'huaxiadraco'),
  ('a_dentelladas', 'plesiopleurodon'),
  ('a_dentelladas', 'ojoraptorsaurus'),
  ('a_dentelladas', 'dromaeosaurus'),
  ('a_dentelladas', 'athenar'),
  ('a_dentelladas', 'sanjuansaurus'),
  ('a_dentelladas', 'suchomimus'),
  ('a_dentelladas', 'eosinopteryx'),
  ('a_dentelladas', 'troodon'),
  ('a_dentelladas', 'carnotaurus'),
  ('a_dentelladas', 'spinosaurus'),
  ('a_dentelladas', 'mosasaurus'),
  ('a_dentelladas', 'halszkaraptor'),
  ('a_dentelladas', 'tongtianlong'),
  ('a_dentelladas', 'scanisaurus'),
  ('a_dentelladas', 'monolophosaurus'),
  ('a_dentelladas', 'invictarx'),
  ('a_dentelladas', 'medusaceratops'),
  ('a_dentelladas', 'platyceratops'),
  ('a_dentelladas', 'loricatosaurus'),
  ('a_dentelladas', 'therizinosaurus'),
  ('a_dentelladas', 'alaskacephale'),
  ('a_dentelladas', 'titanoceratops'),
  ('a_dentelladas', 'atlasaurus'),
  ('a_dentelladas', 'stegoceras'),
  ('a_dentelladas', 'maiasaura'),
  ('a_dentelladas', 'edmontosaurus'),
  ('a_dentelladas', 'plateosauravus'),
  ('a_dentelladas', 'gargoyleosaurus'),
  ('a_dentelladas', 'wendiceratops'),
  ('a_dentelladas', 'antarctosaurus'),
  ('a_dentelladas', 'liaoceratops'),
  ('a_dentelladas', 'rhinorex'),
  ('a_dentelladas', 'bienosaurus'),
  ('a_dentelladas', 'shuangmiaosaurus'),
  ('a_dentelladas', 'chasmosaurus'),
  ('a_dentelladas', 'tyrannosaurus'),
  ('a_dentelladas', 'velociraptor'),
  ('a_dentelladas', 'brachiosaurus'),
  ('a_dentelladas', 'argentinosaurus'),
  ('a_dentelladas', 'mamenchisaurus'),
  ('a_dentelladas', 'amargasaurus'),
  ('a_dentelladas', 'ankylosaurus'),
  ('a_dentelladas', 'kentrosaurus'),
  ('a_dentelladas', 'euoplocephalus'),
  ('a_dentelladas', 'triceratops'),
  ('a_dentelladas', 'pachycephalosaurus'),
  ('a_dentelladas', 'iguanodon'),
  ('a_dentelladas', 'parasaurolophus'),
  ('a_dentelladas', 'pteranodon'),
  ('a_dentelladas', 'quetzalcoatlus'),
  ('a_dentelladas', 'elasmosaurus'),
  ('a_dentelladas', 'gallimimus'),
  ('a_dentelladas', 'thescelosaurus'),
  ('a_dentelladas', 'deinocheirus'),
  ('a_dentelladas', 'anzu'),
  ('a_dentelladas', 'nigersaurus'),
  ('a_dentelladas', 'shuvuuia'),
  ('a_dentelladas', 'saurolophus'),
  ('a_dentelladas', 'tarbosaurus'),
  ('a_dentelladas', 'psittacosaurus'),
  ('a_dentelladas', 'dakotaraptor'),
  ('a_dentelladas', 'carcharodontosaurus'),
  ('a_dentelladas', 'giraffatitan'),
  ('a_dentelladas', 'tupandactylus'),
  ('a_dentelladas', 'rugops'),
  ('a_dentelladas', 'ouranosaurus'),
  ('a_dentelladas', 'deltadromeus'),
  ('a_dentelladas', 'patagotitan'),
  ('a_dentelladas', 'dreadnoughtus'),
  ('a_dentelladas', 'hatzegopteryx'),
  ('a_dentelladas', 'borealopelta'),
  ('a_dentelladas', 'zuul'),
  ('a_dentelladas', 'sauropelta'),
  ('a_dentelladas', 'biomasa'),
  ('a_dentelladas', 'araucarias'),
  ('a_dentelladas', 'ginkgos'),
  ('a_dentelladas', 'cicadas'),
  ('a_dentelladas', 'equisetos'),
  ('a_dentelladas', 'galeria'),
  ('a_dentelladas', 'helechal'),
  ('a_dentelladas', 'vega'),
  ('a_dentelladas', 'humedal'),
  ('a_dentelladas', 'manantial'),
  ('los_pequenos', 'dryosaurus'),
  ('los_pequenos', 'ornitholestes'),
  ('los_pequenos', 'gregarismo'),
  ('los_pequenos', 'gastrolitos'),
  ('los_pequenos', 'crecimiento_acelerado'),
  ('los_pequenos', 'trampa'),
  ('los_pequenos', 'mortandad'),
  ('los_pequenos', 'sabana_helechos'),
  ('los_pequenos', 'canal_trenzado'),
  ('los_pequenos', 'nido'),
  ('los_pequenos', 'cauce_abandonado'),
  ('los_pequenos', 'barrera_troncos'),
  ('los_pequenos', 'carroneros'),
  ('los_pequenos', 'oleada'),
  ('los_pequenos', 'cantera'),
  ('los_pequenos', 'rebrote'),
  ('los_pequenos', 'carrona'),
  ('los_pequenos', 'lago'),
  ('los_pequenos', 'insectos'),
  ('los_pequenos', 'manada_paso'),
  ('los_pequenos', 'frutos'),
  ('los_pequenos', 'llanura'),
  ('los_pequenos', 'canal'),
  ('los_pequenos', 'bosque'),
  ('los_pequenos', 'aridez'),
  ('los_pequenos', 'sabana'),
  ('los_pequenos', 'eosinopteryx'),
  ('los_pequenos', 'troodon'),
  ('los_pequenos', 'halszkaraptor'),
  ('los_pequenos', 'tongtianlong'),
  ('los_pequenos', 'platyceratops'),
  ('los_pequenos', 'liaoceratops'),
  ('los_pequenos', 'bienosaurus'),
  ('los_pequenos', 'velociraptor'),
  ('los_pequenos', 'kentrosaurus'),
  ('los_pequenos', 'pteranodon'),
  ('los_pequenos', 'thescelosaurus'),
  ('los_pequenos', 'shuvuuia'),
  ('los_pequenos', 'psittacosaurus'),
  ('los_pequenos', 'biomasa'),
  ('los_pequenos', 'araucarias'),
  ('los_pequenos', 'ginkgos'),
  ('los_pequenos', 'cicadas'),
  ('los_pequenos', 'equisetos'),
  ('los_pequenos', 'galeria'),
  ('los_pequenos', 'helechal'),
  ('los_pequenos', 'vega'),
  ('los_pequenos', 'humedal'),
  ('los_pequenos', 'manantial')
on conflict (torneo, card_id) do nothing;

delete from public.catalogo_torneo_cartas where (torneo, card_id) not in (values
  ('cada_hueso_uno', 'dryosaurus'),
  ('cada_hueso_uno', 'ornitholestes'),
  ('cada_hueso_uno', 'ceratosaurus'),
  ('cada_hueso_uno', 'stegosaurus'),
  ('cada_hueso_uno', 'allosaurus'),
  ('cada_hueso_uno', 'camarasaurus'),
  ('cada_hueso_uno', 'diplodocus'),
  ('cada_hueso_uno', 'apatosaurus'),
  ('cada_hueso_uno', 'torvosaurus'),
  ('cada_hueso_uno', 'nodosaurus'),
  ('cada_hueso_uno', 'riparovenator'),
  ('cada_hueso_uno', 'lokiceratops'),
  ('cada_hueso_uno', 'brachylophosaurus'),
  ('cada_hueso_uno', 'tyrannotitan'),
  ('cada_hueso_uno', 'huaxiadraco'),
  ('cada_hueso_uno', 'gregarismo'),
  ('cada_hueso_uno', 'gastrolitos'),
  ('cada_hueso_uno', 'crecimiento_acelerado'),
  ('cada_hueso_uno', 'neumaticidad'),
  ('cada_hueso_uno', 'fractura'),
  ('cada_hueso_uno', 'competencia'),
  ('cada_hueso_uno', 'trampa'),
  ('cada_hueso_uno', 'mortandad'),
  ('cada_hueso_uno', 'sabana_helechos'),
  ('cada_hueso_uno', 'inundacion'),
  ('cada_hueso_uno', 'canal_trenzado'),
  ('cada_hueso_uno', 'bosque_ribereno'),
  ('cada_hueso_uno', 'deriva_arida'),
  ('cada_hueso_uno', 'nido'),
  ('cada_hueso_uno', 'tormenta_polvo'),
  ('cada_hueso_uno', 'avenida_lodo'),
  ('cada_hueso_uno', 'enterramiento'),
  ('cada_hueso_uno', 'cauce_abandonado'),
  ('cada_hueso_uno', 'barrera_troncos'),
  ('cada_hueso_uno', 'ceniza'),
  ('cada_hueso_uno', 'sedimento'),
  ('cada_hueso_uno', 'osario'),
  ('cada_hueso_uno', 'carroneros'),
  ('cada_hueso_uno', 'oleada'),
  ('cada_hueso_uno', 'estampida'),
  ('cada_hueso_uno', 'migracion'),
  ('cada_hueso_uno', 'crecida_delta'),
  ('cada_hueso_uno', 'cantera'),
  ('cada_hueso_uno', 'incendio'),
  ('cada_hueso_uno', 'acuifero'),
  ('cada_hueso_uno', 'rebrote'),
  ('cada_hueso_uno', 'carrona'),
  ('cada_hueso_uno', 'lago'),
  ('cada_hueso_uno', 'insectos'),
  ('cada_hueso_uno', 'manada_paso'),
  ('cada_hueso_uno', 'frutos'),
  ('cada_hueso_uno', 'llanura'),
  ('cada_hueso_uno', 'canal'),
  ('cada_hueso_uno', 'bosque'),
  ('cada_hueso_uno', 'aridez'),
  ('cada_hueso_uno', 'sabana'),
  ('cada_hueso_uno', 'plesiopleurodon'),
  ('cada_hueso_uno', 'ojoraptorsaurus'),
  ('cada_hueso_uno', 'dromaeosaurus'),
  ('cada_hueso_uno', 'athenar'),
  ('cada_hueso_uno', 'sanjuansaurus'),
  ('cada_hueso_uno', 'suchomimus'),
  ('cada_hueso_uno', 'eosinopteryx'),
  ('cada_hueso_uno', 'troodon'),
  ('cada_hueso_uno', 'carnotaurus'),
  ('cada_hueso_uno', 'spinosaurus'),
  ('cada_hueso_uno', 'mosasaurus'),
  ('cada_hueso_uno', 'halszkaraptor'),
  ('cada_hueso_uno', 'tongtianlong'),
  ('cada_hueso_uno', 'scanisaurus'),
  ('cada_hueso_uno', 'monolophosaurus'),
  ('cada_hueso_uno', 'invictarx'),
  ('cada_hueso_uno', 'medusaceratops'),
  ('cada_hueso_uno', 'platyceratops'),
  ('cada_hueso_uno', 'loricatosaurus'),
  ('cada_hueso_uno', 'therizinosaurus'),
  ('cada_hueso_uno', 'alaskacephale'),
  ('cada_hueso_uno', 'titanoceratops'),
  ('cada_hueso_uno', 'atlasaurus'),
  ('cada_hueso_uno', 'stegoceras'),
  ('cada_hueso_uno', 'maiasaura'),
  ('cada_hueso_uno', 'edmontosaurus'),
  ('cada_hueso_uno', 'plateosauravus'),
  ('cada_hueso_uno', 'gargoyleosaurus'),
  ('cada_hueso_uno', 'wendiceratops'),
  ('cada_hueso_uno', 'antarctosaurus'),
  ('cada_hueso_uno', 'liaoceratops'),
  ('cada_hueso_uno', 'rhinorex'),
  ('cada_hueso_uno', 'bienosaurus'),
  ('cada_hueso_uno', 'shuangmiaosaurus'),
  ('cada_hueso_uno', 'chasmosaurus'),
  ('cada_hueso_uno', 'tyrannosaurus'),
  ('cada_hueso_uno', 'velociraptor'),
  ('cada_hueso_uno', 'brachiosaurus'),
  ('cada_hueso_uno', 'argentinosaurus'),
  ('cada_hueso_uno', 'mamenchisaurus'),
  ('cada_hueso_uno', 'amargasaurus'),
  ('cada_hueso_uno', 'ankylosaurus'),
  ('cada_hueso_uno', 'kentrosaurus'),
  ('cada_hueso_uno', 'euoplocephalus'),
  ('cada_hueso_uno', 'triceratops'),
  ('cada_hueso_uno', 'pachycephalosaurus'),
  ('cada_hueso_uno', 'iguanodon'),
  ('cada_hueso_uno', 'parasaurolophus'),
  ('cada_hueso_uno', 'pteranodon'),
  ('cada_hueso_uno', 'quetzalcoatlus'),
  ('cada_hueso_uno', 'elasmosaurus'),
  ('cada_hueso_uno', 'gallimimus'),
  ('cada_hueso_uno', 'thescelosaurus'),
  ('cada_hueso_uno', 'deinocheirus'),
  ('cada_hueso_uno', 'anzu'),
  ('cada_hueso_uno', 'nigersaurus'),
  ('cada_hueso_uno', 'shuvuuia'),
  ('cada_hueso_uno', 'saurolophus'),
  ('cada_hueso_uno', 'tarbosaurus'),
  ('cada_hueso_uno', 'psittacosaurus'),
  ('cada_hueso_uno', 'dakotaraptor'),
  ('cada_hueso_uno', 'carcharodontosaurus'),
  ('cada_hueso_uno', 'giraffatitan'),
  ('cada_hueso_uno', 'tupandactylus'),
  ('cada_hueso_uno', 'rugops'),
  ('cada_hueso_uno', 'ouranosaurus'),
  ('cada_hueso_uno', 'deltadromeus'),
  ('cada_hueso_uno', 'patagotitan'),
  ('cada_hueso_uno', 'dreadnoughtus'),
  ('cada_hueso_uno', 'hatzegopteryx'),
  ('cada_hueso_uno', 'borealopelta'),
  ('cada_hueso_uno', 'zuul'),
  ('cada_hueso_uno', 'sauropelta'),
  ('cada_hueso_uno', 'biomasa'),
  ('cada_hueso_uno', 'araucarias'),
  ('cada_hueso_uno', 'ginkgos'),
  ('cada_hueso_uno', 'cicadas'),
  ('cada_hueso_uno', 'equisetos'),
  ('cada_hueso_uno', 'galeria'),
  ('cada_hueso_uno', 'helechal'),
  ('cada_hueso_uno', 'vega'),
  ('cada_hueso_uno', 'humedal'),
  ('cada_hueso_uno', 'manantial'),
  ('sin_colmillos', 'dryosaurus'),
  ('sin_colmillos', 'ornitholestes'),
  ('sin_colmillos', 'ceratosaurus'),
  ('sin_colmillos', 'stegosaurus'),
  ('sin_colmillos', 'diplodocus'),
  ('sin_colmillos', 'brachylophosaurus'),
  ('sin_colmillos', 'huaxiadraco'),
  ('sin_colmillos', 'gregarismo'),
  ('sin_colmillos', 'gastrolitos'),
  ('sin_colmillos', 'neumaticidad'),
  ('sin_colmillos', 'fractura'),
  ('sin_colmillos', 'trampa'),
  ('sin_colmillos', 'sabana_helechos'),
  ('sin_colmillos', 'inundacion'),
  ('sin_colmillos', 'canal_trenzado'),
  ('sin_colmillos', 'bosque_ribereno'),
  ('sin_colmillos', 'deriva_arida'),
  ('sin_colmillos', 'nido'),
  ('sin_colmillos', 'tormenta_polvo'),
  ('sin_colmillos', 'avenida_lodo'),
  ('sin_colmillos', 'enterramiento'),
  ('sin_colmillos', 'cauce_abandonado'),
  ('sin_colmillos', 'barrera_troncos'),
  ('sin_colmillos', 'ceniza'),
  ('sin_colmillos', 'sedimento'),
  ('sin_colmillos', 'osario'),
  ('sin_colmillos', 'carroneros'),
  ('sin_colmillos', 'oleada'),
  ('sin_colmillos', 'estampida'),
  ('sin_colmillos', 'migracion'),
  ('sin_colmillos', 'crecida_delta'),
  ('sin_colmillos', 'cantera'),
  ('sin_colmillos', 'incendio'),
  ('sin_colmillos', 'rebrote'),
  ('sin_colmillos', 'lago'),
  ('sin_colmillos', 'insectos'),
  ('sin_colmillos', 'manada_paso'),
  ('sin_colmillos', 'frutos'),
  ('sin_colmillos', 'llanura'),
  ('sin_colmillos', 'sabana'),
  ('sin_colmillos', 'ojoraptorsaurus'),
  ('sin_colmillos', 'dromaeosaurus'),
  ('sin_colmillos', 'athenar'),
  ('sin_colmillos', 'sanjuansaurus'),
  ('sin_colmillos', 'eosinopteryx'),
  ('sin_colmillos', 'troodon'),
  ('sin_colmillos', 'halszkaraptor'),
  ('sin_colmillos', 'tongtianlong'),
  ('sin_colmillos', 'platyceratops'),
  ('sin_colmillos', 'alaskacephale'),
  ('sin_colmillos', 'stegoceras'),
  ('sin_colmillos', 'plateosauravus'),
  ('sin_colmillos', 'gargoyleosaurus'),
  ('sin_colmillos', 'liaoceratops'),
  ('sin_colmillos', 'bienosaurus'),
  ('sin_colmillos', 'shuangmiaosaurus'),
  ('sin_colmillos', 'chasmosaurus'),
  ('sin_colmillos', 'velociraptor'),
  ('sin_colmillos', 'amargasaurus'),
  ('sin_colmillos', 'kentrosaurus'),
  ('sin_colmillos', 'pachycephalosaurus'),
  ('sin_colmillos', 'iguanodon'),
  ('sin_colmillos', 'pteranodon'),
  ('sin_colmillos', 'gallimimus'),
  ('sin_colmillos', 'thescelosaurus'),
  ('sin_colmillos', 'anzu'),
  ('sin_colmillos', 'shuvuuia'),
  ('sin_colmillos', 'psittacosaurus'),
  ('sin_colmillos', 'rugops'),
  ('sin_colmillos', 'ouranosaurus'),
  ('sin_colmillos', 'zuul'),
  ('sin_colmillos', 'biomasa'),
  ('sin_colmillos', 'araucarias'),
  ('sin_colmillos', 'ginkgos'),
  ('sin_colmillos', 'cicadas'),
  ('sin_colmillos', 'equisetos'),
  ('sin_colmillos', 'galeria'),
  ('sin_colmillos', 'helechal'),
  ('sin_colmillos', 'vega'),
  ('sin_colmillos', 'humedal'),
  ('cielo_y_mar', 'huaxiadraco'),
  ('cielo_y_mar', 'gregarismo'),
  ('cielo_y_mar', 'gastrolitos'),
  ('cielo_y_mar', 'crecimiento_acelerado'),
  ('cielo_y_mar', 'neumaticidad'),
  ('cielo_y_mar', 'fractura'),
  ('cielo_y_mar', 'competencia'),
  ('cielo_y_mar', 'trampa'),
  ('cielo_y_mar', 'mortandad'),
  ('cielo_y_mar', 'sabana_helechos'),
  ('cielo_y_mar', 'inundacion'),
  ('cielo_y_mar', 'canal_trenzado'),
  ('cielo_y_mar', 'bosque_ribereno'),
  ('cielo_y_mar', 'deriva_arida'),
  ('cielo_y_mar', 'nido'),
  ('cielo_y_mar', 'tormenta_polvo'),
  ('cielo_y_mar', 'avenida_lodo'),
  ('cielo_y_mar', 'enterramiento'),
  ('cielo_y_mar', 'cauce_abandonado'),
  ('cielo_y_mar', 'barrera_troncos'),
  ('cielo_y_mar', 'ceniza'),
  ('cielo_y_mar', 'sedimento'),
  ('cielo_y_mar', 'osario'),
  ('cielo_y_mar', 'carroneros'),
  ('cielo_y_mar', 'oleada'),
  ('cielo_y_mar', 'estampida'),
  ('cielo_y_mar', 'migracion'),
  ('cielo_y_mar', 'crecida_delta'),
  ('cielo_y_mar', 'cantera'),
  ('cielo_y_mar', 'incendio'),
  ('cielo_y_mar', 'acuifero'),
  ('cielo_y_mar', 'rebrote'),
  ('cielo_y_mar', 'carrona'),
  ('cielo_y_mar', 'lago'),
  ('cielo_y_mar', 'insectos'),
  ('cielo_y_mar', 'manada_paso'),
  ('cielo_y_mar', 'frutos'),
  ('cielo_y_mar', 'llanura'),
  ('cielo_y_mar', 'canal'),
  ('cielo_y_mar', 'bosque'),
  ('cielo_y_mar', 'aridez'),
  ('cielo_y_mar', 'sabana'),
  ('cielo_y_mar', 'plesiopleurodon'),
  ('cielo_y_mar', 'mosasaurus'),
  ('cielo_y_mar', 'scanisaurus'),
  ('cielo_y_mar', 'pteranodon'),
  ('cielo_y_mar', 'quetzalcoatlus'),
  ('cielo_y_mar', 'elasmosaurus'),
  ('cielo_y_mar', 'tupandactylus'),
  ('cielo_y_mar', 'hatzegopteryx'),
  ('cielo_y_mar', 'biomasa'),
  ('cielo_y_mar', 'araucarias'),
  ('cielo_y_mar', 'ginkgos'),
  ('cielo_y_mar', 'cicadas'),
  ('cielo_y_mar', 'equisetos'),
  ('cielo_y_mar', 'galeria'),
  ('cielo_y_mar', 'helechal'),
  ('cielo_y_mar', 'vega'),
  ('cielo_y_mar', 'humedal'),
  ('cielo_y_mar', 'manantial'),
  ('el_muro', 'stegosaurus'),
  ('el_muro', 'camarasaurus'),
  ('el_muro', 'diplodocus'),
  ('el_muro', 'apatosaurus'),
  ('el_muro', 'nodosaurus'),
  ('el_muro', 'gregarismo'),
  ('el_muro', 'gastrolitos'),
  ('el_muro', 'crecimiento_acelerado'),
  ('el_muro', 'neumaticidad'),
  ('el_muro', 'fractura'),
  ('el_muro', 'competencia'),
  ('el_muro', 'trampa'),
  ('el_muro', 'mortandad'),
  ('el_muro', 'sabana_helechos'),
  ('el_muro', 'inundacion'),
  ('el_muro', 'canal_trenzado'),
  ('el_muro', 'bosque_ribereno'),
  ('el_muro', 'deriva_arida'),
  ('el_muro', 'nido'),
  ('el_muro', 'tormenta_polvo'),
  ('el_muro', 'avenida_lodo'),
  ('el_muro', 'enterramiento'),
  ('el_muro', 'cauce_abandonado'),
  ('el_muro', 'barrera_troncos'),
  ('el_muro', 'ceniza'),
  ('el_muro', 'sedimento'),
  ('el_muro', 'osario'),
  ('el_muro', 'carroneros'),
  ('el_muro', 'oleada'),
  ('el_muro', 'estampida'),
  ('el_muro', 'migracion'),
  ('el_muro', 'crecida_delta'),
  ('el_muro', 'cantera'),
  ('el_muro', 'incendio'),
  ('el_muro', 'acuifero'),
  ('el_muro', 'rebrote'),
  ('el_muro', 'carrona'),
  ('el_muro', 'lago'),
  ('el_muro', 'insectos'),
  ('el_muro', 'manada_paso'),
  ('el_muro', 'frutos'),
  ('el_muro', 'llanura'),
  ('el_muro', 'canal'),
  ('el_muro', 'bosque'),
  ('el_muro', 'aridez'),
  ('el_muro', 'sabana'),
  ('el_muro', 'athenar'),
  ('el_muro', 'invictarx'),
  ('el_muro', 'loricatosaurus'),
  ('el_muro', 'atlasaurus'),
  ('el_muro', 'plateosauravus'),
  ('el_muro', 'gargoyleosaurus'),
  ('el_muro', 'antarctosaurus'),
  ('el_muro', 'bienosaurus'),
  ('el_muro', 'brachiosaurus'),
  ('el_muro', 'argentinosaurus'),
  ('el_muro', 'mamenchisaurus'),
  ('el_muro', 'amargasaurus'),
  ('el_muro', 'ankylosaurus'),
  ('el_muro', 'kentrosaurus'),
  ('el_muro', 'euoplocephalus'),
  ('el_muro', 'nigersaurus'),
  ('el_muro', 'giraffatitan'),
  ('el_muro', 'patagotitan'),
  ('el_muro', 'dreadnoughtus'),
  ('el_muro', 'borealopelta'),
  ('el_muro', 'zuul'),
  ('el_muro', 'sauropelta'),
  ('el_muro', 'biomasa'),
  ('el_muro', 'araucarias'),
  ('el_muro', 'ginkgos'),
  ('el_muro', 'cicadas'),
  ('el_muro', 'equisetos'),
  ('el_muro', 'galeria'),
  ('el_muro', 'helechal'),
  ('el_muro', 'vega'),
  ('el_muro', 'humedal'),
  ('el_muro', 'manantial'),
  ('sin_trampas', 'dryosaurus'),
  ('sin_trampas', 'ornitholestes'),
  ('sin_trampas', 'ceratosaurus'),
  ('sin_trampas', 'stegosaurus'),
  ('sin_trampas', 'allosaurus'),
  ('sin_trampas', 'camarasaurus'),
  ('sin_trampas', 'diplodocus'),
  ('sin_trampas', 'apatosaurus'),
  ('sin_trampas', 'torvosaurus'),
  ('sin_trampas', 'nodosaurus'),
  ('sin_trampas', 'riparovenator'),
  ('sin_trampas', 'lokiceratops'),
  ('sin_trampas', 'brachylophosaurus'),
  ('sin_trampas', 'tyrannotitan'),
  ('sin_trampas', 'huaxiadraco'),
  ('sin_trampas', 'cantera'),
  ('sin_trampas', 'rebrote'),
  ('sin_trampas', 'carrona'),
  ('sin_trampas', 'lago'),
  ('sin_trampas', 'insectos'),
  ('sin_trampas', 'manada_paso'),
  ('sin_trampas', 'frutos'),
  ('sin_trampas', 'llanura'),
  ('sin_trampas', 'canal'),
  ('sin_trampas', 'bosque'),
  ('sin_trampas', 'aridez'),
  ('sin_trampas', 'sabana'),
  ('sin_trampas', 'plesiopleurodon'),
  ('sin_trampas', 'ojoraptorsaurus'),
  ('sin_trampas', 'dromaeosaurus'),
  ('sin_trampas', 'athenar'),
  ('sin_trampas', 'sanjuansaurus'),
  ('sin_trampas', 'suchomimus'),
  ('sin_trampas', 'eosinopteryx'),
  ('sin_trampas', 'troodon'),
  ('sin_trampas', 'carnotaurus'),
  ('sin_trampas', 'spinosaurus'),
  ('sin_trampas', 'mosasaurus'),
  ('sin_trampas', 'halszkaraptor'),
  ('sin_trampas', 'tongtianlong'),
  ('sin_trampas', 'scanisaurus'),
  ('sin_trampas', 'monolophosaurus'),
  ('sin_trampas', 'invictarx'),
  ('sin_trampas', 'medusaceratops'),
  ('sin_trampas', 'platyceratops'),
  ('sin_trampas', 'loricatosaurus'),
  ('sin_trampas', 'therizinosaurus'),
  ('sin_trampas', 'alaskacephale'),
  ('sin_trampas', 'titanoceratops'),
  ('sin_trampas', 'atlasaurus'),
  ('sin_trampas', 'stegoceras'),
  ('sin_trampas', 'maiasaura'),
  ('sin_trampas', 'edmontosaurus'),
  ('sin_trampas', 'plateosauravus'),
  ('sin_trampas', 'gargoyleosaurus'),
  ('sin_trampas', 'wendiceratops'),
  ('sin_trampas', 'antarctosaurus'),
  ('sin_trampas', 'liaoceratops'),
  ('sin_trampas', 'rhinorex'),
  ('sin_trampas', 'bienosaurus'),
  ('sin_trampas', 'shuangmiaosaurus'),
  ('sin_trampas', 'chasmosaurus'),
  ('sin_trampas', 'tyrannosaurus'),
  ('sin_trampas', 'velociraptor'),
  ('sin_trampas', 'brachiosaurus'),
  ('sin_trampas', 'argentinosaurus'),
  ('sin_trampas', 'mamenchisaurus'),
  ('sin_trampas', 'amargasaurus'),
  ('sin_trampas', 'ankylosaurus'),
  ('sin_trampas', 'kentrosaurus'),
  ('sin_trampas', 'euoplocephalus'),
  ('sin_trampas', 'triceratops'),
  ('sin_trampas', 'pachycephalosaurus'),
  ('sin_trampas', 'iguanodon'),
  ('sin_trampas', 'parasaurolophus'),
  ('sin_trampas', 'pteranodon'),
  ('sin_trampas', 'quetzalcoatlus'),
  ('sin_trampas', 'elasmosaurus'),
  ('sin_trampas', 'gallimimus'),
  ('sin_trampas', 'thescelosaurus'),
  ('sin_trampas', 'deinocheirus'),
  ('sin_trampas', 'anzu'),
  ('sin_trampas', 'nigersaurus'),
  ('sin_trampas', 'shuvuuia'),
  ('sin_trampas', 'saurolophus'),
  ('sin_trampas', 'tarbosaurus'),
  ('sin_trampas', 'psittacosaurus'),
  ('sin_trampas', 'dakotaraptor'),
  ('sin_trampas', 'carcharodontosaurus'),
  ('sin_trampas', 'giraffatitan'),
  ('sin_trampas', 'tupandactylus'),
  ('sin_trampas', 'rugops'),
  ('sin_trampas', 'ouranosaurus'),
  ('sin_trampas', 'deltadromeus'),
  ('sin_trampas', 'patagotitan'),
  ('sin_trampas', 'dreadnoughtus'),
  ('sin_trampas', 'hatzegopteryx'),
  ('sin_trampas', 'borealopelta'),
  ('sin_trampas', 'zuul'),
  ('sin_trampas', 'sauropelta'),
  ('sin_trampas', 'biomasa'),
  ('sin_trampas', 'araucarias'),
  ('sin_trampas', 'ginkgos'),
  ('sin_trampas', 'cicadas'),
  ('sin_trampas', 'equisetos'),
  ('sin_trampas', 'galeria'),
  ('sin_trampas', 'helechal'),
  ('sin_trampas', 'vega'),
  ('sin_trampas', 'humedal'),
  ('sin_trampas', 'manantial'),
  ('a_dentelladas', 'dryosaurus'),
  ('a_dentelladas', 'ornitholestes'),
  ('a_dentelladas', 'ceratosaurus'),
  ('a_dentelladas', 'stegosaurus'),
  ('a_dentelladas', 'allosaurus'),
  ('a_dentelladas', 'camarasaurus'),
  ('a_dentelladas', 'diplodocus'),
  ('a_dentelladas', 'apatosaurus'),
  ('a_dentelladas', 'torvosaurus'),
  ('a_dentelladas', 'nodosaurus'),
  ('a_dentelladas', 'riparovenator'),
  ('a_dentelladas', 'lokiceratops'),
  ('a_dentelladas', 'brachylophosaurus'),
  ('a_dentelladas', 'tyrannotitan'),
  ('a_dentelladas', 'huaxiadraco'),
  ('a_dentelladas', 'plesiopleurodon'),
  ('a_dentelladas', 'ojoraptorsaurus'),
  ('a_dentelladas', 'dromaeosaurus'),
  ('a_dentelladas', 'athenar'),
  ('a_dentelladas', 'sanjuansaurus'),
  ('a_dentelladas', 'suchomimus'),
  ('a_dentelladas', 'eosinopteryx'),
  ('a_dentelladas', 'troodon'),
  ('a_dentelladas', 'carnotaurus'),
  ('a_dentelladas', 'spinosaurus'),
  ('a_dentelladas', 'mosasaurus'),
  ('a_dentelladas', 'halszkaraptor'),
  ('a_dentelladas', 'tongtianlong'),
  ('a_dentelladas', 'scanisaurus'),
  ('a_dentelladas', 'monolophosaurus'),
  ('a_dentelladas', 'invictarx'),
  ('a_dentelladas', 'medusaceratops'),
  ('a_dentelladas', 'platyceratops'),
  ('a_dentelladas', 'loricatosaurus'),
  ('a_dentelladas', 'therizinosaurus'),
  ('a_dentelladas', 'alaskacephale'),
  ('a_dentelladas', 'titanoceratops'),
  ('a_dentelladas', 'atlasaurus'),
  ('a_dentelladas', 'stegoceras'),
  ('a_dentelladas', 'maiasaura'),
  ('a_dentelladas', 'edmontosaurus'),
  ('a_dentelladas', 'plateosauravus'),
  ('a_dentelladas', 'gargoyleosaurus'),
  ('a_dentelladas', 'wendiceratops'),
  ('a_dentelladas', 'antarctosaurus'),
  ('a_dentelladas', 'liaoceratops'),
  ('a_dentelladas', 'rhinorex'),
  ('a_dentelladas', 'bienosaurus'),
  ('a_dentelladas', 'shuangmiaosaurus'),
  ('a_dentelladas', 'chasmosaurus'),
  ('a_dentelladas', 'tyrannosaurus'),
  ('a_dentelladas', 'velociraptor'),
  ('a_dentelladas', 'brachiosaurus'),
  ('a_dentelladas', 'argentinosaurus'),
  ('a_dentelladas', 'mamenchisaurus'),
  ('a_dentelladas', 'amargasaurus'),
  ('a_dentelladas', 'ankylosaurus'),
  ('a_dentelladas', 'kentrosaurus'),
  ('a_dentelladas', 'euoplocephalus'),
  ('a_dentelladas', 'triceratops'),
  ('a_dentelladas', 'pachycephalosaurus'),
  ('a_dentelladas', 'iguanodon'),
  ('a_dentelladas', 'parasaurolophus'),
  ('a_dentelladas', 'pteranodon'),
  ('a_dentelladas', 'quetzalcoatlus'),
  ('a_dentelladas', 'elasmosaurus'),
  ('a_dentelladas', 'gallimimus'),
  ('a_dentelladas', 'thescelosaurus'),
  ('a_dentelladas', 'deinocheirus'),
  ('a_dentelladas', 'anzu'),
  ('a_dentelladas', 'nigersaurus'),
  ('a_dentelladas', 'shuvuuia'),
  ('a_dentelladas', 'saurolophus'),
  ('a_dentelladas', 'tarbosaurus'),
  ('a_dentelladas', 'psittacosaurus'),
  ('a_dentelladas', 'dakotaraptor'),
  ('a_dentelladas', 'carcharodontosaurus'),
  ('a_dentelladas', 'giraffatitan'),
  ('a_dentelladas', 'tupandactylus'),
  ('a_dentelladas', 'rugops'),
  ('a_dentelladas', 'ouranosaurus'),
  ('a_dentelladas', 'deltadromeus'),
  ('a_dentelladas', 'patagotitan'),
  ('a_dentelladas', 'dreadnoughtus'),
  ('a_dentelladas', 'hatzegopteryx'),
  ('a_dentelladas', 'borealopelta'),
  ('a_dentelladas', 'zuul'),
  ('a_dentelladas', 'sauropelta'),
  ('a_dentelladas', 'biomasa'),
  ('a_dentelladas', 'araucarias'),
  ('a_dentelladas', 'ginkgos'),
  ('a_dentelladas', 'cicadas'),
  ('a_dentelladas', 'equisetos'),
  ('a_dentelladas', 'galeria'),
  ('a_dentelladas', 'helechal'),
  ('a_dentelladas', 'vega'),
  ('a_dentelladas', 'humedal'),
  ('a_dentelladas', 'manantial'),
  ('los_pequenos', 'dryosaurus'),
  ('los_pequenos', 'ornitholestes'),
  ('los_pequenos', 'gregarismo'),
  ('los_pequenos', 'gastrolitos'),
  ('los_pequenos', 'crecimiento_acelerado'),
  ('los_pequenos', 'trampa'),
  ('los_pequenos', 'mortandad'),
  ('los_pequenos', 'sabana_helechos'),
  ('los_pequenos', 'canal_trenzado'),
  ('los_pequenos', 'nido'),
  ('los_pequenos', 'cauce_abandonado'),
  ('los_pequenos', 'barrera_troncos'),
  ('los_pequenos', 'carroneros'),
  ('los_pequenos', 'oleada'),
  ('los_pequenos', 'cantera'),
  ('los_pequenos', 'rebrote'),
  ('los_pequenos', 'carrona'),
  ('los_pequenos', 'lago'),
  ('los_pequenos', 'insectos'),
  ('los_pequenos', 'manada_paso'),
  ('los_pequenos', 'frutos'),
  ('los_pequenos', 'llanura'),
  ('los_pequenos', 'canal'),
  ('los_pequenos', 'bosque'),
  ('los_pequenos', 'aridez'),
  ('los_pequenos', 'sabana'),
  ('los_pequenos', 'eosinopteryx'),
  ('los_pequenos', 'troodon'),
  ('los_pequenos', 'halszkaraptor'),
  ('los_pequenos', 'tongtianlong'),
  ('los_pequenos', 'platyceratops'),
  ('los_pequenos', 'liaoceratops'),
  ('los_pequenos', 'bienosaurus'),
  ('los_pequenos', 'velociraptor'),
  ('los_pequenos', 'kentrosaurus'),
  ('los_pequenos', 'pteranodon'),
  ('los_pequenos', 'thescelosaurus'),
  ('los_pequenos', 'shuvuuia'),
  ('los_pequenos', 'psittacosaurus'),
  ('los_pequenos', 'biomasa'),
  ('los_pequenos', 'araucarias'),
  ('los_pequenos', 'ginkgos'),
  ('los_pequenos', 'cicadas'),
  ('los_pequenos', 'equisetos'),
  ('los_pequenos', 'galeria'),
  ('los_pequenos', 'helechal'),
  ('los_pequenos', 'vega'),
  ('los_pequenos', 'humedal'),
  ('los_pequenos', 'manantial')
);

delete from public.catalogo_torneos where id not in (
  'cada_hueso_uno',
  'sin_colmillos',
  'cielo_y_mar',
  'el_muro',
  'sin_trampas',
  'a_dentelladas',
  'los_pequenos'
);

insert into public.catalogo_torneo_premios (victorias, monedas, sobres) values
  (0, 0, 0),
  (1, 0, 0),
  (2, 50, 0),
  (3, 100, 0),
  (4, 0, 1),
  (5, 0, 2)
on conflict (victorias) do update set monedas = excluded.monedas, sobres = excluded.sobres;

delete from public.catalogo_torneo_premios where victorias > 5;

delete from public.catalogo_cartas where card_id not in (
  'dryosaurus',
  'ornitholestes',
  'ceratosaurus',
  'stegosaurus',
  'allosaurus',
  'camarasaurus',
  'diplodocus',
  'apatosaurus',
  'torvosaurus',
  'nodosaurus',
  'riparovenator',
  'lokiceratops',
  'brachylophosaurus',
  'tyrannotitan',
  'huaxiadraco',
  'gregarismo',
  'gastrolitos',
  'crecimiento_acelerado',
  'neumaticidad',
  'fractura',
  'competencia',
  'trampa',
  'mortandad',
  'sabana_helechos',
  'inundacion',
  'canal_trenzado',
  'bosque_ribereno',
  'deriva_arida',
  'nido',
  'tormenta_polvo',
  'avenida_lodo',
  'enterramiento',
  'cauce_abandonado',
  'barrera_troncos',
  'ceniza',
  'sedimento',
  'osario',
  'carroneros',
  'oleada',
  'estampida',
  'migracion',
  'crecida_delta',
  'cantera',
  'incendio',
  'acuifero',
  'rebrote',
  'carrona',
  'lago',
  'insectos',
  'manada_paso',
  'frutos',
  'llanura',
  'canal',
  'bosque',
  'aridez',
  'sabana',
  'plesiopleurodon',
  'ojoraptorsaurus',
  'dromaeosaurus',
  'athenar',
  'sanjuansaurus',
  'suchomimus',
  'eosinopteryx',
  'troodon',
  'carnotaurus',
  'spinosaurus',
  'mosasaurus',
  'halszkaraptor',
  'tongtianlong',
  'scanisaurus',
  'monolophosaurus',
  'invictarx',
  'medusaceratops',
  'platyceratops',
  'loricatosaurus',
  'therizinosaurus',
  'alaskacephale',
  'titanoceratops',
  'atlasaurus',
  'stegoceras',
  'maiasaura',
  'edmontosaurus',
  'plateosauravus',
  'gargoyleosaurus',
  'wendiceratops',
  'antarctosaurus',
  'liaoceratops',
  'rhinorex',
  'bienosaurus',
  'shuangmiaosaurus',
  'chasmosaurus',
  'tyrannosaurus',
  'velociraptor',
  'brachiosaurus',
  'argentinosaurus',
  'mamenchisaurus',
  'amargasaurus',
  'ankylosaurus',
  'kentrosaurus',
  'euoplocephalus',
  'triceratops',
  'pachycephalosaurus',
  'iguanodon',
  'parasaurolophus',
  'pteranodon',
  'quetzalcoatlus',
  'elasmosaurus',
  'gallimimus',
  'thescelosaurus',
  'deinocheirus',
  'anzu',
  'nigersaurus',
  'shuvuuia',
  'saurolophus',
  'tarbosaurus',
  'psittacosaurus',
  'dakotaraptor',
  'carcharodontosaurus',
  'giraffatitan',
  'tupandactylus',
  'rugops',
  'ouranosaurus',
  'deltadromeus',
  'patagotitan',
  'dreadnoughtus',
  'hatzegopteryx',
  'borealopelta',
  'zuul',
  'sauropelta',
  'biomasa',
  'araucarias',
  'ginkgos',
  'cicadas',
  'equisetos',
  'galeria',
  'helechal',
  'vega',
  'humedal',
  'manantial',
  'jefe_saurophaganax',
  'jefe_barosaurus',
  'jefe_supersaurus',
  'jefe_hesperosaurus',
  'jefe_harpactognathus'
);

insert into public.catalogo_economia
  (id, precio_sobre, cartas_por_sobre, monedas_inicio, monedas_victoria,
   monedas_derrota, tamano_mazo, mazos_maximo, legendarias_dino_max,
   torneo_entrada, torneo_victorias, torneo_derrotas)
values (1, 300, 5, 300, 30, 0, 55, 12, 3, 50, 5, 3)
on conflict (id) do update set
  precio_sobre = excluded.precio_sobre,
  cartas_por_sobre = excluded.cartas_por_sobre,
  monedas_inicio = excluded.monedas_inicio,
  monedas_victoria = excluded.monedas_victoria,
  monedas_derrota = excluded.monedas_derrota,
  tamano_mazo = excluded.tamano_mazo,
  mazos_maximo = excluded.mazos_maximo,
  legendarias_dino_max = excluded.legendarias_dino_max,
  torneo_entrada = excluded.torneo_entrada,
  torneo_victorias = excluded.torneo_victorias,
  torneo_derrotas = excluded.torneo_derrotas;

-- El catálogo lo lee cualquiera que haya entrado: son las reglas del
-- juego, no datos de nadie. Escribirlo, sólo las migraciones.
alter table public.catalogo_cartas enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_cartas;
create policy "el catálogo es público" on public.catalogo_cartas
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_cartas from anon, authenticated;
revoke select on public.catalogo_cartas from anon;

alter table public.catalogo_inicial enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_inicial;
create policy "el catálogo es público" on public.catalogo_inicial
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_inicial from anon, authenticated;
revoke select on public.catalogo_inicial from anon;

alter table public.catalogo_iniciales enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_iniciales;
create policy "el catálogo es público" on public.catalogo_iniciales
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_iniciales from anon, authenticated;
revoke select on public.catalogo_iniciales from anon;

alter table public.catalogo_cosmeticos enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_cosmeticos;
create policy "el catálogo es público" on public.catalogo_cosmeticos
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_cosmeticos from anon, authenticated;
revoke select on public.catalogo_cosmeticos from anon;

alter table public.catalogo_crafteo enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_crafteo;
create policy "el catálogo es público" on public.catalogo_crafteo
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_crafteo from anon, authenticated;
revoke select on public.catalogo_crafteo from anon;

alter table public.catalogo_economia enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_economia;
create policy "el catálogo es público" on public.catalogo_economia
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_economia from anon, authenticated;
revoke select on public.catalogo_economia from anon;

alter table public.catalogo_torneos enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_torneos;
create policy "el catálogo es público" on public.catalogo_torneos
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_torneos from anon, authenticated;
revoke select on public.catalogo_torneos from anon;

alter table public.catalogo_torneo_cartas enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_torneo_cartas;
create policy "el catálogo es público" on public.catalogo_torneo_cartas
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_torneo_cartas from anon, authenticated;
revoke select on public.catalogo_torneo_cartas from anon;

alter table public.catalogo_torneo_premios enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_torneo_premios;
create policy "el catálogo es público" on public.catalogo_torneo_premios
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_torneo_premios from anon, authenticated;
revoke select on public.catalogo_torneo_premios from anon;
