-- DinoWar — catálogo de cartas. GENERADO por
-- `node tools/generar-cartas.mjs` desde src/data/cards.js,
-- src/data/balance.js y src/data/coleccion.js. **No editar a mano.**
--
-- El servidor necesita esto para tres cosas que no puede preguntarle al
-- cliente: si un mazo respeta las rarezas, si las cartas que lleva son
-- tuyas de verdad, y con qué colección empieza una cuenta nueva. Un test
-- comprueba que este fichero es el que saldría hoy del código.

create table if not exists public.catalogo_cartas (
  card_id      text primary key,
  tipo         text not null,
  rareza       text not null,
  -- Copias que caben en un mazo. Es a la vez el límite de construcción y
  -- la escala de rareza: la misma regla mirada desde dos sitios.
  copias_max   int  not null check (copias_max > 0),
  valor_fusion int  not null check (valor_fusion >= 0),
  -- Las de jefe se ganan cooperando, no salen en sobres y no se funden.
  es_jefe      boolean not null default false
);

-- Con qué colección empieza una cuenta. Es justo el mazo de referencia:
-- lo necesario para jugar desde el primer minuto y ni una carta más.
create table if not exists public.catalogo_inicial (
  card_id  text primary key references public.catalogo_cartas (card_id),
  copias   int not null check (copias > 0)
);

-- Los mazos iniciales: uno se elige al crear la cuenta y es la colección
-- de salida entera. `private.sembrar_inicial` (0023) lee de aquí; el
-- cliente sólo manda el id del mazo. Sale de src/data/iniciales.js.
create table if not exists public.catalogo_iniciales (
  mazo     text not null,
  nombre   text not null,
  card_id  text not null references public.catalogo_cartas (card_id),
  copias   int not null check (copias > 0),
  primary key (mazo, card_id)
);

-- La tienda: lo que se vende y cuánto cuesta. `comprar_cosmetico` (0024) cobra
-- el precio de AQUÍ; el cliente sólo manda el id. Sale de src/data/cosmeticos.js.
create table if not exists public.catalogo_cosmeticos (
  id           text primary key,
  tipo         text not null,
  precio       int  not null check (precio >= 0),
  por_defecto  boolean not null default false
);
-- Lo exclusivo cuesta 0 y NO se compra ni es de todos: lo otorga un logro.
-- La columna llegó después de la tabla (0027), de ahí el `add column`.
alter table public.catalogo_cosmeticos
  add column if not exists exclusivo boolean not null default false;

-- Los precios, en una fila. Que sean una tabla y no constantes en el SQL
-- permite tocarlos sin volver a desplegar nada.
create table if not exists public.catalogo_economia (
  id                int primary key default 1 check (id = 1),
  precio_sobre      int not null,
  cartas_por_sobre  int not null,
  monedas_inicio    int not null,
  monedas_victoria  int not null,
  monedas_derrota   int not null,
  tamano_mazo       int not null,
  mazos_maximo      int not null
);

-- Criaturas legendarias que caben en un mazo, entre todas. La columna
-- llegó después de la tabla, de ahí el `add column`: sin él una base ya
-- creada se queda sin ella y `validar_mazo` no puede leer el tope.
alter table public.catalogo_economia
  add column if not exists legendarias_dino_max int not null default 3;

-- El crafteo: cuántas esquirlas da fundir una copia sobrante y cuántas cuesta
-- crear una, por rareza. `fundir_excedente` y `crear_carta` (0029) leen de
-- AQUÍ; el cliente sólo manda el id. Sale de src/data/crafteo.js.
create table if not exists public.catalogo_crafteo (
  rareza  text primary key,
  fundir  int not null check (fundir > 0),
  crear   int not null check (crear > 0)
);

insert into public.catalogo_cartas (card_id, tipo, rareza, copias_max, valor_fusion, es_jefe) values
  ('dryosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('ornitholestes', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('ceratosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('stegosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('allosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('camarasaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('diplodocus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('apatosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('torvosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('nodosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('riparovenator', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('lokiceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('brachylophosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('tyrannotitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('huaxiadraco', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('gregarismo', 'EVENTO', 'RARO', 3, 12, false),
  ('gastrolitos', 'EVENTO', 'EPICO', 2, 35, false),
  ('crecimiento_acelerado', 'EVENTO', 'LEGENDARIO', 1, 100, false),
  ('neumaticidad', 'EVENTO', 'EPICO', 2, 35, false),
  ('fractura', 'EVENTO', 'EPICO', 2, 35, false),
  ('competencia', 'EVENTO', 'EPICO', 2, 35, false),
  ('trampa', 'EVENTO', 'RARO', 3, 12, false),
  ('mortandad', 'EVENTO', 'LEGENDARIO', 1, 100, false),
  ('sabana_helechos', 'EVENTO', 'COMUN', 3, 4, false),
  ('inundacion', 'EVENTO', 'RARO', 3, 12, false),
  ('canal_trenzado', 'EVENTO', 'RARO', 3, 12, false),
  ('bosque_ribereno', 'EVENTO', 'EPICO', 2, 35, false),
  ('deriva_arida', 'EVENTO', 'EPICO', 2, 35, false),
  ('nido', 'EVENTO', 'COMUN', 3, 4, false),
  ('tormenta_polvo', 'EVENTO', 'RARO', 3, 12, false),
  ('avenida_lodo', 'EVENTO', 'EPICO', 2, 35, false),
  ('enterramiento', 'EVENTO', 'RARO', 3, 12, false),
  ('cauce_abandonado', 'EVENTO', 'COMUN', 3, 4, false),
  ('barrera_troncos', 'EVENTO', 'COMUN', 3, 4, false),
  ('ceniza', 'EVENTO', 'RARO', 3, 12, false),
  ('sedimento', 'EVENTO', 'EPICO', 2, 35, false),
  ('osario', 'EVENTO', 'RARO', 3, 12, false),
  ('carroneros', 'EVENTO', 'COMUN', 3, 4, false),
  ('oleada', 'EVENTO', 'COMUN', 3, 4, false),
  ('estampida', 'EVENTO', 'EPICO', 2, 35, false),
  ('migracion', 'EVENTO', 'RARO', 3, 12, false),
  ('crecida_delta', 'EVENTO', 'RARO', 3, 12, false),
  ('cantera', 'RECURSO', 'EPICO', 2, 35, false),
  ('incendio', 'EVENTO', 'RARO', 3, 12, false),
  ('acuifero', 'EVENTO', 'EPICO', 2, 35, false),
  ('rebrote', 'RECURSO', 'RARO', 3, 12, false),
  ('carrona', 'RECURSO', 'LEGENDARIO', 1, 100, false),
  ('lago', 'RECURSO', 'EPICO', 2, 35, false),
  ('insectos', 'RECURSO', 'COMUN', 3, 4, false),
  ('manada_paso', 'RECURSO', 'RARO', 3, 12, false),
  ('frutos', 'RECURSO', 'RARO', 3, 12, false),
  ('llanura', 'CLIMA', 'EPICO', 2, 35, false),
  ('canal', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('bosque', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('aridez', 'CLIMA', 'LEGENDARIO', 1, 100, false),
  ('sabana', 'CLIMA', 'COMUN', 3, 4, false),
  ('plesiopleurodon', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('ojoraptorsaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('dromaeosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('athenar', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('sanjuansaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('suchomimus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('eosinopteryx', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('troodon', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('carnotaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('spinosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('mosasaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('halszkaraptor', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('tongtianlong', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('scanisaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('monolophosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('invictarx', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('medusaceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('platyceratops', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('loricatosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('therizinosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('alaskacephale', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('titanoceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('atlasaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('stegoceras', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('maiasaura', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('edmontosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('plateosauravus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('gargoyleosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('wendiceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('antarctosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('liaoceratops', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('rhinorex', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('bienosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('shuangmiaosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('chasmosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('tyrannosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('velociraptor', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('brachiosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('argentinosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('mamenchisaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('amargasaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('ankylosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('kentrosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('euoplocephalus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('triceratops', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('pachycephalosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('iguanodon', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('parasaurolophus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('pteranodon', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('quetzalcoatlus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('elasmosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('gallimimus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('thescelosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('deinocheirus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('anzu', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('nigersaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('shuvuuia', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('saurolophus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('tarbosaurus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('psittacosaurus', 'DINOSAURIO', 'COMUN', 3, 4, false),
  ('dakotaraptor', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('carcharodontosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('giraffatitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('tupandactylus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('rugops', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('ouranosaurus', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('deltadromeus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('patagotitan', 'DINOSAURIO', 'LEGENDARIO', 1, 100, false),
  ('dreadnoughtus', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('hatzegopteryx', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('borealopelta', 'DINOSAURIO', 'EPICO', 2, 35, false),
  ('zuul', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('sauropelta', 'DINOSAURIO', 'RARO', 3, 12, false),
  ('biomasa', 'BIOMASA', 'COMUN', 7, 4, false),
  ('araucarias', 'BIOMASA', 'COMUN', 3, 4, false),
  ('ginkgos', 'BIOMASA', 'COMUN', 3, 4, false),
  ('cicadas', 'BIOMASA', 'COMUN', 3, 4, false),
  ('equisetos', 'BIOMASA', 'COMUN', 3, 4, false),
  ('galeria', 'BIOMASA', 'COMUN', 3, 4, false),
  ('helechal', 'BIOMASA', 'COMUN', 3, 4, false),
  ('vega', 'BIOMASA', 'EPICO', 2, 35, false),
  ('humedal', 'BIOMASA', 'EPICO', 2, 35, false),
  ('manantial', 'BIOMASA', 'LEGENDARIO', 1, 100, false),
  ('jefe_saurophaganax', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_barosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_supersaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_hesperosaurus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true),
  ('jefe_harpactognathus', 'DINOSAURIO', 'LEGENDARIO', 1, 100, true)
on conflict (card_id) do update set
  tipo = excluded.tipo, rareza = excluded.rareza,
  copias_max = excluded.copias_max, valor_fusion = excluded.valor_fusion,
  es_jefe = excluded.es_jefe;

insert into public.catalogo_inicial (card_id, copias) values
  ('dryosaurus', 3),
  ('ornitholestes', 2),
  ('ceratosaurus', 2),
  ('stegosaurus', 1),
  ('kentrosaurus', 2),
  ('velociraptor', 2),
  ('allosaurus', 2),
  ('camarasaurus', 1),
  ('amargasaurus', 2),
  ('iguanodon', 2),
  ('pachycephalosaurus', 2),
  ('riparovenator', 1),
  ('lokiceratops', 1),
  ('huaxiadraco', 1),
  ('brachylophosaurus', 1),
  ('diplodocus', 1),
  ('apatosaurus', 1),
  ('tyrannotitan', 1),
  ('gregarismo', 2),
  ('trampa', 2),
  ('rebrote', 2),
  ('nido', 2),
  ('sabana_helechos', 2),
  ('insectos', 2),
  ('fractura', 2),
  ('gastrolitos', 1),
  ('crecimiento_acelerado', 1),
  ('sabana', 1),
  ('canal_trenzado', 1),
  ('biomasa', 5),
  ('araucarias', 2),
  ('cicadas', 2)
on conflict (card_id) do update set copias = excluded.copias;

delete from public.catalogo_inicial where card_id not in (
  'dryosaurus',
  'ornitholestes',
  'ceratosaurus',
  'stegosaurus',
  'kentrosaurus',
  'velociraptor',
  'allosaurus',
  'camarasaurus',
  'amargasaurus',
  'iguanodon',
  'pachycephalosaurus',
  'riparovenator',
  'lokiceratops',
  'huaxiadraco',
  'brachylophosaurus',
  'diplodocus',
  'apatosaurus',
  'tyrannotitan',
  'gregarismo',
  'trampa',
  'rebrote',
  'nido',
  'sabana_helechos',
  'insectos',
  'fractura',
  'gastrolitos',
  'crecimiento_acelerado',
  'sabana',
  'canal_trenzado',
  'biomasa',
  'araucarias',
  'cicadas'
);

insert into public.catalogo_iniciales (mazo, nombre, card_id, copias) values
  ('teropodos', 'Cazadores', 'ornitholestes', 3),
  ('teropodos', 'Cazadores', 'ceratosaurus', 3),
  ('teropodos', 'Cazadores', 'dromaeosaurus', 3),
  ('teropodos', 'Cazadores', 'velociraptor', 3),
  ('teropodos', 'Cazadores', 'therizinosaurus', 2),
  ('teropodos', 'Cazadores', 'ojoraptorsaurus', 2),
  ('teropodos', 'Cazadores', 'sanjuansaurus', 3),
  ('teropodos', 'Cazadores', 'allosaurus', 3),
  ('teropodos', 'Cazadores', 'riparovenator', 2),
  ('teropodos', 'Cazadores', 'carnotaurus', 2),
  ('teropodos', 'Cazadores', 'torvosaurus', 1),
  ('teropodos', 'Cazadores', 'tyrannotitan', 1),
  ('teropodos', 'Cazadores', 'gregarismo', 2),
  ('teropodos', 'Cazadores', 'trampa', 2),
  ('teropodos', 'Cazadores', 'rebrote', 2),
  ('teropodos', 'Cazadores', 'nido', 2),
  ('teropodos', 'Cazadores', 'sabana_helechos', 2),
  ('teropodos', 'Cazadores', 'insectos', 2),
  ('teropodos', 'Cazadores', 'fractura', 2),
  ('teropodos', 'Cazadores', 'gastrolitos', 1),
  ('teropodos', 'Cazadores', 'crecimiento_acelerado', 1),
  ('teropodos', 'Cazadores', 'sabana', 1),
  ('teropodos', 'Cazadores', 'canal_trenzado', 1),
  ('teropodos', 'Cazadores', 'biomasa', 5),
  ('teropodos', 'Cazadores', 'araucarias', 2),
  ('teropodos', 'Cazadores', 'cicadas', 2),
  ('sauropodos', 'Gigantes', 'plateosauravus', 3),
  ('sauropodos', 'Gigantes', 'athenar', 3),
  ('sauropodos', 'Gigantes', 'amargasaurus', 3),
  ('sauropodos', 'Gigantes', 'diplodocus', 3),
  ('sauropodos', 'Gigantes', 'apatosaurus', 2),
  ('sauropodos', 'Gigantes', 'camarasaurus', 2),
  ('sauropodos', 'Gigantes', 'mamenchisaurus', 3),
  ('sauropodos', 'Gigantes', 'atlasaurus', 1),
  ('sauropodos', 'Gigantes', 'brachiosaurus', 1),
  ('sauropodos', 'Gigantes', 'ceratosaurus', 3),
  ('sauropodos', 'Gigantes', 'velociraptor', 3),
  ('sauropodos', 'Gigantes', 'ornitholestes', 1),
  ('sauropodos', 'Gigantes', 'gregarismo', 2),
  ('sauropodos', 'Gigantes', 'trampa', 2),
  ('sauropodos', 'Gigantes', 'rebrote', 2),
  ('sauropodos', 'Gigantes', 'nido', 2),
  ('sauropodos', 'Gigantes', 'sabana_helechos', 2),
  ('sauropodos', 'Gigantes', 'insectos', 2),
  ('sauropodos', 'Gigantes', 'fractura', 2),
  ('sauropodos', 'Gigantes', 'gastrolitos', 1),
  ('sauropodos', 'Gigantes', 'crecimiento_acelerado', 1),
  ('sauropodos', 'Gigantes', 'sabana', 1),
  ('sauropodos', 'Gigantes', 'canal_trenzado', 1),
  ('sauropodos', 'Gigantes', 'biomasa', 5),
  ('sauropodos', 'Gigantes', 'araucarias', 2),
  ('sauropodos', 'Gigantes', 'cicadas', 2),
  ('ornitopodos', 'Manadas', 'dryosaurus', 3),
  ('ornitopodos', 'Manadas', 'shuangmiaosaurus', 3),
  ('ornitopodos', 'Manadas', 'iguanodon', 3),
  ('ornitopodos', 'Manadas', 'brachylophosaurus', 3),
  ('ornitopodos', 'Manadas', 'parasaurolophus', 3),
  ('ornitopodos', 'Manadas', 'rhinorex', 2),
  ('ornitopodos', 'Manadas', 'maiasaura', 1),
  ('ornitopodos', 'Manadas', 'edmontosaurus', 1),
  ('ornitopodos', 'Manadas', 'pachycephalosaurus', 2),
  ('ornitopodos', 'Manadas', 'allosaurus', 1),
  ('ornitopodos', 'Manadas', 'ornitholestes', 1),
  ('ornitopodos', 'Manadas', 'velociraptor', 3),
  ('ornitopodos', 'Manadas', 'ceratosaurus', 2),
  ('ornitopodos', 'Manadas', 'gregarismo', 2),
  ('ornitopodos', 'Manadas', 'trampa', 2),
  ('ornitopodos', 'Manadas', 'rebrote', 2),
  ('ornitopodos', 'Manadas', 'nido', 2),
  ('ornitopodos', 'Manadas', 'sabana_helechos', 2),
  ('ornitopodos', 'Manadas', 'insectos', 2),
  ('ornitopodos', 'Manadas', 'fractura', 2),
  ('ornitopodos', 'Manadas', 'gastrolitos', 1),
  ('ornitopodos', 'Manadas', 'crecimiento_acelerado', 1),
  ('ornitopodos', 'Manadas', 'sabana', 1),
  ('ornitopodos', 'Manadas', 'canal_trenzado', 1),
  ('ornitopodos', 'Manadas', 'biomasa', 5),
  ('ornitopodos', 'Manadas', 'araucarias', 2),
  ('ornitopodos', 'Manadas', 'cicadas', 2)
on conflict (mazo, card_id) do update set nombre = excluded.nombre, copias = excluded.copias;

delete from public.catalogo_iniciales where (mazo, card_id) not in (values
  ('teropodos', 'ornitholestes'),
  ('teropodos', 'ceratosaurus'),
  ('teropodos', 'dromaeosaurus'),
  ('teropodos', 'velociraptor'),
  ('teropodos', 'therizinosaurus'),
  ('teropodos', 'ojoraptorsaurus'),
  ('teropodos', 'sanjuansaurus'),
  ('teropodos', 'allosaurus'),
  ('teropodos', 'riparovenator'),
  ('teropodos', 'carnotaurus'),
  ('teropodos', 'torvosaurus'),
  ('teropodos', 'tyrannotitan'),
  ('teropodos', 'gregarismo'),
  ('teropodos', 'trampa'),
  ('teropodos', 'rebrote'),
  ('teropodos', 'nido'),
  ('teropodos', 'sabana_helechos'),
  ('teropodos', 'insectos'),
  ('teropodos', 'fractura'),
  ('teropodos', 'gastrolitos'),
  ('teropodos', 'crecimiento_acelerado'),
  ('teropodos', 'sabana'),
  ('teropodos', 'canal_trenzado'),
  ('teropodos', 'biomasa'),
  ('teropodos', 'araucarias'),
  ('teropodos', 'cicadas'),
  ('sauropodos', 'plateosauravus'),
  ('sauropodos', 'athenar'),
  ('sauropodos', 'amargasaurus'),
  ('sauropodos', 'diplodocus'),
  ('sauropodos', 'apatosaurus'),
  ('sauropodos', 'camarasaurus'),
  ('sauropodos', 'mamenchisaurus'),
  ('sauropodos', 'atlasaurus'),
  ('sauropodos', 'brachiosaurus'),
  ('sauropodos', 'ceratosaurus'),
  ('sauropodos', 'velociraptor'),
  ('sauropodos', 'ornitholestes'),
  ('sauropodos', 'gregarismo'),
  ('sauropodos', 'trampa'),
  ('sauropodos', 'rebrote'),
  ('sauropodos', 'nido'),
  ('sauropodos', 'sabana_helechos'),
  ('sauropodos', 'insectos'),
  ('sauropodos', 'fractura'),
  ('sauropodos', 'gastrolitos'),
  ('sauropodos', 'crecimiento_acelerado'),
  ('sauropodos', 'sabana'),
  ('sauropodos', 'canal_trenzado'),
  ('sauropodos', 'biomasa'),
  ('sauropodos', 'araucarias'),
  ('sauropodos', 'cicadas'),
  ('ornitopodos', 'dryosaurus'),
  ('ornitopodos', 'shuangmiaosaurus'),
  ('ornitopodos', 'iguanodon'),
  ('ornitopodos', 'brachylophosaurus'),
  ('ornitopodos', 'parasaurolophus'),
  ('ornitopodos', 'rhinorex'),
  ('ornitopodos', 'maiasaura'),
  ('ornitopodos', 'edmontosaurus'),
  ('ornitopodos', 'pachycephalosaurus'),
  ('ornitopodos', 'allosaurus'),
  ('ornitopodos', 'ornitholestes'),
  ('ornitopodos', 'velociraptor'),
  ('ornitopodos', 'ceratosaurus'),
  ('ornitopodos', 'gregarismo'),
  ('ornitopodos', 'trampa'),
  ('ornitopodos', 'rebrote'),
  ('ornitopodos', 'nido'),
  ('ornitopodos', 'sabana_helechos'),
  ('ornitopodos', 'insectos'),
  ('ornitopodos', 'fractura'),
  ('ornitopodos', 'gastrolitos'),
  ('ornitopodos', 'crecimiento_acelerado'),
  ('ornitopodos', 'sabana'),
  ('ornitopodos', 'canal_trenzado'),
  ('ornitopodos', 'biomasa'),
  ('ornitopodos', 'araucarias'),
  ('ornitopodos', 'cicadas')
);

insert into public.catalogo_cosmeticos (id, tipo, precio, por_defecto, exclusivo) values
  ('dorso_clasico', 'DORSO', 0, true, false),
  ('dorso_ambar', 'DORSO', 300, false, false),
  ('dorso_obsidiana', 'DORSO', 300, false, false),
  ('dorso_morrison', 'DORSO', 300, false, false),
  ('dorso_hell_creek', 'DORSO', 300, false, false),
  ('dorso_kem_kem', 'DORSO', 300, false, false),
  ('dorso_volcan', 'DORSO', 300, false, false),
  ('dorso_cazador', 'DORSO', 0, false, true),
  ('tapete_clasico', 'TAPETE', 0, true, false),
  ('tapete_ambar', 'TAPETE', 500, false, false),
  ('tapete_obsidiana', 'TAPETE', 500, false, false),
  ('tapete_morrison', 'TAPETE', 500, false, false),
  ('tapete_volcan', 'TAPETE', 500, false, false),
  ('tapete_hell_creek', 'TAPETE', 500, false, false),
  ('tapete_kem_kem', 'TAPETE', 500, false, false),
  ('tapete_solnhofen', 'TAPETE', 500, false, false),
  ('tapete_excavacion', 'TAPETE', 500, false, false),
  ('estandarte_clasico', 'ESTANDARTE', 0, true, false),
  ('estandarte_ambar', 'ESTANDARTE', 400, false, false),
  ('estandarte_obsidiana', 'ESTANDARTE', 400, false, false),
  ('estandarte_fosil', 'ESTANDARTE', 400, false, false),
  ('estandarte_volcan', 'ESTANDARTE', 400, false, false),
  ('estandarte_helecho', 'ESTANDARTE', 400, false, false),
  ('estandarte_campeon', 'ESTANDARTE', 0, false, true),
  ('retrato_paleontologa', 'RETRATO', 0, true, false),
  ('retrato_buscador', 'RETRATO', 0, false, false),
  ('retrato_amonite', 'RETRATO', 350, false, false),
  ('retrato_huevo', 'RETRATO', 350, false, false),
  ('retrato_placas', 'RETRATO', 350, false, false),
  ('retrato_cientifico', 'RETRATO', 350, false, false),
  ('retrato_cientifica', 'RETRATO', 350, false, false),
  ('retrato_cazador', 'RETRATO', 350, false, false),
  ('retrato_trex', 'RETRATO', 350, false, false),
  ('retrato_saurophaganax', 'RETRATO', 0, false, true),
  ('retrato_barosaurus', 'RETRATO', 0, false, true),
  ('retrato_supersaurus', 'RETRATO', 0, false, true),
  ('retrato_hesperosaurus', 'RETRATO', 0, false, true),
  ('retrato_harpactognathus', 'RETRATO', 0, false, true),
  ('titulo_ninguno', 'TITULO', 0, true, false),
  ('titulo_duelista', 'TITULO', 0, false, true),
  ('titulo_asaltante', 'TITULO', 0, false, true),
  ('titulo_cazador', 'TITULO', 0, false, true),
  ('titulo_campeon', 'TITULO', 0, false, true)
on conflict (id) do update set tipo = excluded.tipo, precio = excluded.precio,
  por_defecto = excluded.por_defecto, exclusivo = excluded.exclusivo;

delete from public.catalogo_cosmeticos where id not in (
  'dorso_clasico',
  'dorso_ambar',
  'dorso_obsidiana',
  'dorso_morrison',
  'dorso_hell_creek',
  'dorso_kem_kem',
  'dorso_volcan',
  'dorso_cazador',
  'tapete_clasico',
  'tapete_ambar',
  'tapete_obsidiana',
  'tapete_morrison',
  'tapete_volcan',
  'tapete_hell_creek',
  'tapete_kem_kem',
  'tapete_solnhofen',
  'tapete_excavacion',
  'estandarte_clasico',
  'estandarte_ambar',
  'estandarte_obsidiana',
  'estandarte_fosil',
  'estandarte_volcan',
  'estandarte_helecho',
  'estandarte_campeon',
  'retrato_paleontologa',
  'retrato_buscador',
  'retrato_amonite',
  'retrato_huevo',
  'retrato_placas',
  'retrato_cientifico',
  'retrato_cientifica',
  'retrato_cazador',
  'retrato_trex',
  'retrato_saurophaganax',
  'retrato_barosaurus',
  'retrato_supersaurus',
  'retrato_hesperosaurus',
  'retrato_harpactognathus',
  'titulo_ninguno',
  'titulo_duelista',
  'titulo_asaltante',
  'titulo_cazador',
  'titulo_campeon'
);

insert into public.catalogo_crafteo (rareza, fundir, crear) values
  ('COMUN', 10, 80),
  ('RARO', 30, 200),
  ('EPICO', 150, 500),
  ('LEGENDARIO', 400, 1600)
on conflict (rareza) do update set fundir = excluded.fundir, crear = excluded.crear;

delete from public.catalogo_cartas where card_id not in (
  'dryosaurus',
  'ornitholestes',
  'ceratosaurus',
  'stegosaurus',
  'allosaurus',
  'camarasaurus',
  'diplodocus',
  'apatosaurus',
  'torvosaurus',
  'nodosaurus',
  'riparovenator',
  'lokiceratops',
  'brachylophosaurus',
  'tyrannotitan',
  'huaxiadraco',
  'gregarismo',
  'gastrolitos',
  'crecimiento_acelerado',
  'neumaticidad',
  'fractura',
  'competencia',
  'trampa',
  'mortandad',
  'sabana_helechos',
  'inundacion',
  'canal_trenzado',
  'bosque_ribereno',
  'deriva_arida',
  'nido',
  'tormenta_polvo',
  'avenida_lodo',
  'enterramiento',
  'cauce_abandonado',
  'barrera_troncos',
  'ceniza',
  'sedimento',
  'osario',
  'carroneros',
  'oleada',
  'estampida',
  'migracion',
  'crecida_delta',
  'cantera',
  'incendio',
  'acuifero',
  'rebrote',
  'carrona',
  'lago',
  'insectos',
  'manada_paso',
  'frutos',
  'llanura',
  'canal',
  'bosque',
  'aridez',
  'sabana',
  'plesiopleurodon',
  'ojoraptorsaurus',
  'dromaeosaurus',
  'athenar',
  'sanjuansaurus',
  'suchomimus',
  'eosinopteryx',
  'troodon',
  'carnotaurus',
  'spinosaurus',
  'mosasaurus',
  'halszkaraptor',
  'tongtianlong',
  'scanisaurus',
  'monolophosaurus',
  'invictarx',
  'medusaceratops',
  'platyceratops',
  'loricatosaurus',
  'therizinosaurus',
  'alaskacephale',
  'titanoceratops',
  'atlasaurus',
  'stegoceras',
  'maiasaura',
  'edmontosaurus',
  'plateosauravus',
  'gargoyleosaurus',
  'wendiceratops',
  'antarctosaurus',
  'liaoceratops',
  'rhinorex',
  'bienosaurus',
  'shuangmiaosaurus',
  'chasmosaurus',
  'tyrannosaurus',
  'velociraptor',
  'brachiosaurus',
  'argentinosaurus',
  'mamenchisaurus',
  'amargasaurus',
  'ankylosaurus',
  'kentrosaurus',
  'euoplocephalus',
  'triceratops',
  'pachycephalosaurus',
  'iguanodon',
  'parasaurolophus',
  'pteranodon',
  'quetzalcoatlus',
  'elasmosaurus',
  'gallimimus',
  'thescelosaurus',
  'deinocheirus',
  'anzu',
  'nigersaurus',
  'shuvuuia',
  'saurolophus',
  'tarbosaurus',
  'psittacosaurus',
  'dakotaraptor',
  'carcharodontosaurus',
  'giraffatitan',
  'tupandactylus',
  'rugops',
  'ouranosaurus',
  'deltadromeus',
  'patagotitan',
  'dreadnoughtus',
  'hatzegopteryx',
  'borealopelta',
  'zuul',
  'sauropelta',
  'biomasa',
  'araucarias',
  'ginkgos',
  'cicadas',
  'equisetos',
  'galeria',
  'helechal',
  'vega',
  'humedal',
  'manantial',
  'jefe_saurophaganax',
  'jefe_barosaurus',
  'jefe_supersaurus',
  'jefe_hesperosaurus',
  'jefe_harpactognathus'
);

insert into public.catalogo_economia
  (id, precio_sobre, cartas_por_sobre, monedas_inicio, monedas_victoria,
   monedas_derrota, tamano_mazo, mazos_maximo, legendarias_dino_max)
values (1, 100, 5, 240, 50, 0, 55, 12, 3)
on conflict (id) do update set
  precio_sobre = excluded.precio_sobre,
  cartas_por_sobre = excluded.cartas_por_sobre,
  monedas_inicio = excluded.monedas_inicio,
  monedas_victoria = excluded.monedas_victoria,
  monedas_derrota = excluded.monedas_derrota,
  tamano_mazo = excluded.tamano_mazo,
  mazos_maximo = excluded.mazos_maximo,
  legendarias_dino_max = excluded.legendarias_dino_max;

-- El catálogo lo lee cualquiera que haya entrado: son las reglas del
-- juego, no datos de nadie. Escribirlo, sólo las migraciones.
alter table public.catalogo_cartas enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_cartas;
create policy "el catálogo es público" on public.catalogo_cartas
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_cartas from anon, authenticated;
revoke select on public.catalogo_cartas from anon;

alter table public.catalogo_inicial enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_inicial;
create policy "el catálogo es público" on public.catalogo_inicial
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_inicial from anon, authenticated;
revoke select on public.catalogo_inicial from anon;

alter table public.catalogo_iniciales enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_iniciales;
create policy "el catálogo es público" on public.catalogo_iniciales
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_iniciales from anon, authenticated;
revoke select on public.catalogo_iniciales from anon;

alter table public.catalogo_cosmeticos enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_cosmeticos;
create policy "el catálogo es público" on public.catalogo_cosmeticos
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_cosmeticos from anon, authenticated;
revoke select on public.catalogo_cosmeticos from anon;

alter table public.catalogo_crafteo enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_crafteo;
create policy "el catálogo es público" on public.catalogo_crafteo
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_crafteo from anon, authenticated;
revoke select on public.catalogo_crafteo from anon;

alter table public.catalogo_economia enable row level security;
drop policy if exists "el catálogo es público" on public.catalogo_economia;
create policy "el catálogo es público" on public.catalogo_economia
  for select to authenticated using (true);
revoke insert, update, delete on public.catalogo_economia from anon, authenticated;
revoke select on public.catalogo_economia from anon;
